//! The proto contract: the wire schema a gRPC build compiles, rendered from
//! the model like every other surface.

use heck::{ToSnakeCase, ToUpperCamelCase};

use super::*;

/// The proto package a service's contract lives in: the model and service names
/// lowercased, collapsed to one segment when they match.
pub(super) fn proto_package(model: &Model, service: &Service) -> String {
    let model_name = model.name.to_lowercase();
    let service_name = service.name.to_lowercase();
    if model_name == service_name {
        model_name
    } else {
        format!("{model_name}.{service_name}")
    }
}

/// Render the proto contract a gRPC inbound serves: one message per request
/// struct the service's operations take, a message per contract type those
/// fields reference — a rich enum becomes a message holding a `oneof` over its
/// variants — a wrapper message per response label, and the service with one
/// rpc per operation. A response the model holds as a foreign type carries its
/// JSON rendering in a `json` field. The build compiles the file, so the wire
/// schema is a projection of the model like every other surface.
pub fn render_proto(model: &Model, service: &Service) -> Result<String, RenderError> {
    validate_render_inputs(model)?;
    if !model.services.iter().any(|modeled| modeled == service) {
        return Err(RenderError::ServiceNotModeled {
            service: service.name.clone(),
        });
    }
    validate_proto_inputs(model, service)?;
    let package = proto_package(model, service);
    let mut out = String::from("// @generated by `theseus generate` — do not edit by hand.\n");
    out.push_str("syntax = \"proto3\";\n\n");
    out.push_str(&format!("package {package};\n"));

    let mut rendered: Vec<String> = Vec::new();
    let mut referenced: Vec<String> = Vec::new();
    for op in &service.operations {
        let request = proto_request_message(op, model)?;
        if !rendered.contains(&request.0) {
            out.push_str(&format!("\n{}", request.1));
            rendered.push(request.0);
        }
        if let Some(def) = request_type(op, model)
            && let TypeShape::Struct(fields) = &def.shape
        {
            referenced.extend(referenced_message_labels(fields, model));
        }
        let response = proto_response_message(op, model)?;
        if !rendered.contains(&response.0) {
            out.push_str(&format!("\n{}", response.1));
            rendered.push(response.0);
        }
    }

    // Each contract type the request fields reference renders as its own
    // message, and a struct's fields may reference further ones.
    while let Some(label) = referenced.pop() {
        if rendered.contains(&label) {
            continue;
        }
        let Some(def) = model.type_def(&label) else {
            continue;
        };
        match &def.shape {
            TypeShape::Enum { variants, .. } => {
                out.push_str(&format!(
                    "\n{}",
                    proto_enum_message(&def.name, variants, model)?
                ));
                rendered.push(label);
                for variant in variants {
                    referenced.extend(referenced_message_labels(&variant.fields, model));
                }
            }
            TypeShape::Struct(fields) => {
                let mut body = format!("message {} {{\n", def.name);
                push_proto_fields(&mut body, fields, model, "  ")?;
                body.push_str("}\n");
                out.push_str(&format!("\n{body}"));
                rendered.push(label);
                referenced.extend(referenced_message_labels(fields, model));
            }
            _ => {}
        }
    }

    out.push_str(&format!("\nservice {} {{\n", pascal_case(&service.name)));
    for op in &service.operations {
        let rpc = pascal_case(&op.name);
        let request = proto_request_message(op, model)?.0;
        let response = proto_response_message(op, model)?.0;
        push_proto_comment(&mut out, &op.summary, "  ");
        out.push_str(&format!("  rpc {rpc} ({request}) returns ({response});\n"));
    }
    out.push_str("}\n");
    protox_parse::parse("generated.proto", &out).map_err(|error| RenderError::InvalidProto {
        service: service.name.clone(),
        message: error.to_string(),
    })?;
    Ok(out)
}

/// Validate every protobuf token the service projection emits, including
/// transitively referenced request messages.
pub(super) fn validate_proto_inputs(model: &Model, service: &Service) -> Result<(), RenderError> {
    for segment in proto_package(model, service).split('.') {
        validate_proto_identifier("protobuf package segment", segment)?;
    }
    validate_proto_identifier("protobuf service", &pascal_case(&service.name))?;
    validate_proto_upper_camel("protobuf service", &pascal_case(&service.name))?;

    let mut pending = Vec::new();
    for op in &service.operations {
        validate_proto_identifier("protobuf RPC", &pascal_case(&op.name))?;
        validate_proto_snake("protobuf operation", &op.name)?;
        if let Some(def) = request_type(op, model) {
            validate_proto_identifier("protobuf request message", &def.name)?;
            validate_proto_upper_camel("protobuf request message", &def.name)?;
            if let TypeShape::Struct(fields) = &def.shape {
                validate_proto_fields(fields, model, &mut pending)?;
            }
        } else {
            validate_proto_identifier("protobuf request message", "Empty")?;
        }

        if op.response == "Empty" {
            continue;
        }
        validate_proto_identifier("protobuf response message", &op.response)?;
        validate_proto_upper_camel("protobuf response message", &op.response)?;
        if let Some(TypeShape::Struct(fields)) = model.type_def(&op.response).map(|def| &def.shape)
        {
            validate_proto_fields(fields, model, &mut pending)?;
        }
    }

    let mut seen = Vec::new();
    while let Some(label) = pending.pop() {
        if seen.contains(&label) {
            continue;
        }
        seen.push(label.clone());
        let Some(def) = model.type_def(&label) else {
            continue;
        };
        validate_proto_identifier("protobuf message", &def.name)?;
        validate_proto_upper_camel("protobuf message", &def.name)?;
        match &def.shape {
            TypeShape::Struct(fields) => validate_proto_fields(fields, model, &mut pending)?,
            TypeShape::Enum { variants, .. } => {
                for variant in variants {
                    validate_proto_identifier(
                        "protobuf variant message",
                        &pascal_case(&variant.name),
                    )?;
                    validate_proto_identifier("protobuf oneof field", &variant.name)?;
                    validate_proto_snake("protobuf oneof field", &variant.name)?;
                    validate_proto_fields(&variant.fields, model, &mut pending)?;
                }
            }
            _ => {}
        }
    }
    Ok(())
}

fn validate_proto_fields(
    fields: &[Field],
    model: &Model,
    pending: &mut Vec<String>,
) -> Result<(), RenderError> {
    for field in fields {
        validate_proto_identifier("protobuf field", &field.name)?;
        validate_proto_snake("protobuf field", &field.name)?;
        proto_type(&field.ty, model, &field.name)?;
        pending.extend(referenced_message_labels(
            std::slice::from_ref(field),
            model,
        ));
    }
    Ok(())
}

fn validate_proto_identifier(kind: &'static str, name: &str) -> Result<(), RenderError> {
    let mut chars = name.chars();
    let starts_valid = chars
        .next()
        .is_some_and(|ch| ch == '_' || ch.is_ascii_alphabetic());
    let rest_valid = chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric());
    if starts_valid && rest_valid {
        Ok(())
    } else {
        Err(RenderError::InvalidProtoIdentifier {
            kind,
            name: name.to_string(),
        })
    }
}

fn validate_proto_snake(kind: &'static str, name: &str) -> Result<(), RenderError> {
    if name.to_snake_case() == name {
        Ok(())
    } else {
        Err(RenderError::InvalidProtoIdentifier {
            kind,
            name: name.to_string(),
        })
    }
}

fn validate_proto_upper_camel(kind: &'static str, name: &str) -> Result<(), RenderError> {
    if name.to_upper_camel_case() == name {
        Ok(())
    } else {
        Err(RenderError::InvalidProtoIdentifier {
            kind,
            name: name.to_string(),
        })
    }
}

/// The contract types a set of fields references that render as messages of
/// their own: the base label of each field, stripped of its containers, when it
/// names a defined struct or enum.
pub(super) fn referenced_message_labels(fields: &[Field], model: &Model) -> Vec<String> {
    fields
        .iter()
        .filter_map(|field| {
            let base = base_label(&field.ty);
            model
                .type_def(base)
                .filter(|def| matches!(def.shape, TypeShape::Struct(_) | TypeShape::Enum { .. }))
                .map(|def| def.name.clone())
        })
        .collect()
}

/// Render a rich enum as a proto message: one nested message per variant, and a
/// `oneof` over them named for the enum's tag, so an edit is one message
/// carrying exactly one verb.
pub(super) fn proto_enum_message(
    name: &str,
    variants: &[Variant],
    model: &Model,
) -> Result<String, RenderError> {
    let mut body = format!("message {name} {{\n");
    for variant in variants {
        body.push_str(&format!("  message {} {{\n", pascal_case(&variant.name)));
        push_proto_fields(&mut body, &variant.fields, model, "    ")?;
        body.push_str("  }\n");
    }
    body.push_str("\n  oneof verb {\n");
    for (index, variant) in variants.iter().enumerate() {
        body.push_str(&format!(
            "    {} {} = {};\n",
            pascal_case(&variant.name),
            variant.name,
            index + 1
        ));
    }
    body.push_str("  }\n}\n");
    Ok(body)
}

/// Append a set of fields to a proto message body at the given indent.
pub(super) fn push_proto_fields(
    body: &mut String,
    fields: &[Field],
    model: &Model,
    indent: &str,
) -> Result<(), RenderError> {
    for (index, field) in fields.iter().enumerate() {
        push_proto_comment(body, &field.doc, indent);
        body.push_str(&format!(
            "{indent}{} {} = {};\n",
            proto_type(&field.ty, model, &field.name)?,
            field.name,
            index + 1
        ));
    }
    Ok(())
}

/// Render every comment line with its own marker so modeled prose cannot inject
/// protobuf declarations through a newline.
fn push_proto_comment(body: &mut String, text: &str, indent: &str) {
    for line in text.lines() {
        body.push_str(&format!("{indent}// {line}\n"));
    }
}

/// The proto message an operation's request maps to: its struct rendered field
/// by field, or `Empty` for an operation that takes none. Returns the message
/// name and its definition.
pub(super) fn proto_request_message(
    op: &Operation,
    model: &Model,
) -> Result<(String, String), RenderError> {
    match request_type(op, model) {
        Some(def) => {
            let TypeShape::Struct(fields) = &def.shape else {
                return Ok(empty_message());
            };
            let mut body = format!("message {} {{\n", def.name);
            push_proto_fields(&mut body, fields, model, "  ")?;
            body.push_str("}\n");
            Ok((def.name.clone(), body))
        }
        None => Ok(empty_message()),
    }
}

/// The proto message an operation's response maps to: a wrapper carrying one
/// `value` for a label that resolves to a string, `Empty` for none, the struct
/// rendered field by field, or — for a label the model holds as a foreign type —
/// a wrapper carrying the response's JSON rendering.
pub(super) fn proto_response_message(
    op: &Operation,
    model: &Model,
) -> Result<(String, String), RenderError> {
    if op.response == "Empty" {
        return Ok(empty_message());
    }
    match rust_type(&op.response, model).as_str() {
        "String" => Ok((
            op.response.clone(),
            format!("message {} {{\n  string value = 1;\n}}\n", op.response),
        )),
        _ => match model.type_def(&op.response).map(|def| &def.shape) {
            Some(TypeShape::Struct(fields)) => {
                let mut body = format!("message {} {{\n", op.response);
                push_proto_fields(&mut body, fields, model, "  ")?;
                body.push_str("}\n");
                Ok((op.response.clone(), body))
            }
            _ => Ok((
                op.response.clone(),
                format!(
                    "// The JSON rendering of the `{}` response.\nmessage {} {{\n  string json = 1;\n}}\n",
                    op.response, op.response
                ),
            )),
        },
    }
}

pub(super) fn empty_message() -> (String, String) {
    ("Empty".to_string(), "message Empty {}\n".to_string())
}

/// The proto type a contract type label maps to. A map field is a proto map —
/// never optional, absent as empty — matching a contract field that defaults.
pub(super) fn proto_type(label: &str, model: &Model, field: &str) -> Result<String, RenderError> {
    if let Some(inner) = optional_inner(label) {
        let inner = proto_type(inner, model, field)?;
        if inner.starts_with("map<") {
            return Ok(inner);
        }
        return Ok(format!("optional {inner}"));
    }
    if let Some(inner) = vec_inner(label) {
        return Ok(format!("repeated {}", proto_type(inner, model, field)?));
    }
    if let Some(value) = map_value(label) {
        return Ok(format!("map<string, {}>", proto_type(value, model, field)?));
    }
    let rendered = match label {
        "String" => "string".to_string(),
        "bool" => "bool".to_string(),
        "f64" => "double".to_string(),
        "f32" => "float".to_string(),
        "i32" | "i8" | "i16" => "int32".to_string(),
        "i64" | "isize" => "int64".to_string(),
        "u32" | "u8" | "u16" => "uint32".to_string(),
        "u64" | "usize" => "uint64".to_string(),
        other => match model.type_def(other).map(|def| &def.shape) {
            Some(TypeShape::Struct(_) | TypeShape::Enum { .. }) => other.to_string(),
            _ => {
                return Err(RenderError::UnsupportedGrpcFieldType {
                    field: field.to_string(),
                    ty: label.to_string(),
                });
            }
        },
    };
    Ok(rendered)
}
