// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the gRPC service glue and its status map.

/// The wire types and service glue the build compiles from the proto.
pub mod proto {
    tonic::include_proto!("theseus");
}

/// The service glue: the transport's generated server trait, implemented
/// over any implementation of the service contract.
pub struct GrpcTheseus<S>(pub S);

#[tonic::async_trait]
impl<S: theseus::TheseusService + Send + Sync + 'static> proto::theseus_server::Theseus
for GrpcTheseus<S> {
    async fn model(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::ModelDocument>, tonic::Status> {
        let outcome = self.0.model();
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::ModelDocument { value })),
            Err(error) => Err(status(&error)),
        }
    }
    async fn verify(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::VerifyReport>, tonic::Status> {
        let outcome = self.0.verify();
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::VerifyReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
    async fn generate(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::GeneratedFiles>, tonic::Status> {
        let outcome = self.0.generate();
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::GeneratedFiles { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
    async fn query(
        &self,
        request: tonic::Request<proto::QueryRequest>,
    ) -> Result<tonic::Response<proto::QueryResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .query(theseus::QueryRequest {
                find: request.find,
                node: request.node,
                kind: request.kind,
            });
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::QueryResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
    async fn patch(
        &self,
        request: tonic::Request<proto::PatchRequest>,
    ) -> Result<tonic::Response<proto::PatchResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .patch(theseus::PatchRequest {
                edit: request
                    .edit
                    .into_iter()
                    .map(edit_from_proto)
                    .collect::<Result<Vec<_>, tonic::Status>>()?,
                write: request.write,
            });
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::PatchResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
    async fn coverage(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CoverageReport>, tonic::Status> {
        let outcome = self.0.coverage();
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::CoverageReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
    async fn implement(
        &self,
        request: tonic::Request<proto::ImplementRequest>,
    ) -> Result<tonic::Response<proto::ImplementResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .implement(theseus::ImplementRequest {
                method: request.method,
                body: request.body,
            });
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::ImplementResult { value })),
            Err(error) => Err(status(&error)),
        }
    }
    async fn show(
        &self,
        request: tonic::Request<proto::ShowRequest>,
    ) -> Result<tonic::Response<proto::HandlerSource>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .show(theseus::ShowRequest {
                method: request.method,
            });
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::HandlerSource { value })),
            Err(error) => Err(status(&error)),
        }
    }
    async fn check(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CheckReport>, tonic::Status> {
        let outcome = self.0.check();
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CheckReport { value })),
            Err(error) => Err(status(&error)),
        }
    }
    async fn calc(
        &self,
        request: tonic::Request<proto::CalcRequest>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .calc(theseus::CalcRequest {
                op: request.op,
                a: request.a,
                b: request.b,
            });
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }
    async fn scaffold(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::GeneratedFiles>, tonic::Status> {
        let outcome = self.0.scaffold();
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::GeneratedFiles { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }
}

/// Convert the wire's Edit to the contract's, verb by verb.
fn edit_from_proto(value: proto::Edit) -> Result<theseus_modeling::Edit, tonic::Status> {
    match value.verb {
        Some(proto::edit::Verb::Add(data)) => {
            Ok(theseus_modeling::Edit::Add {
                parent: data.parent,
                kind: data.kind,
                name: data.name,
                attrs: data.attrs.into_iter().collect(),
            })
        }
        Some(proto::edit::Verb::Remove(data)) => {
            Ok(theseus_modeling::Edit::Remove {
                target: data.target,
            })
        }
        Some(proto::edit::Verb::Rename(data)) => {
            Ok(theseus_modeling::Edit::Rename {
                target: data.target,
                to: data.to,
            })
        }
        Some(proto::edit::Verb::Set(data)) => {
            Ok(theseus_modeling::Edit::Set {
                target: data.target,
                attrs: data.attrs.into_iter().collect(),
            })
        }
        None => Err(tonic::Status::invalid_argument("a Edit carries one verb")),
    }
}

/// The status an operation error maps to, read from the error's type: an
/// operation on its trait default is UNIMPLEMENTED, a write the gate refused
/// is PERMISSION_DENIED, and anything else is INTERNAL.
fn status(error: &anyhow::Error) -> tonic::Status {
    if error.downcast_ref::<theseus::Unimplemented>().is_some() {
        tonic::Status::unimplemented(error.to_string())
    } else if error.downcast_ref::<theseus_modeling::Refused>().is_some() {
        tonic::Status::permission_denied(error.to_string())
    } else {
        tonic::Status::internal(error.to_string())
    }
}
