// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the gRPC service glue and its status map.

/// The wire types and service glue the build compiles from the proto.
pub mod proto {
    tonic::include_proto!("theseus");
}

/// The service glue: the transport's generated server trait, implemented
/// over any implementation of the service contract.
pub struct GrpcTheseus<S>(pub S);

#[tonic::async_trait]
impl<S: theseus::TheseusService + Send + Sync + 'static> proto::theseus_server::Theseus
for GrpcTheseus<S> {
    async fn model(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::ModelDocument>, tonic::Status> {
        let outcome = self.0.model().await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::ModelDocument { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn verify(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::VerifyReport>, tonic::Status> {
        let outcome = self.0.verify().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::VerifyReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn generate(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::GeneratedFiles>, tonic::Status> {
        let outcome = self.0.generate().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::GeneratedFiles { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn query(
        &self,
        request: tonic::Request<proto::QueryRequest>,
    ) -> Result<tonic::Response<proto::QueryResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .query(theseus::QueryRequest {
                find: request.find,
                node: request.node,
                kind: request.kind,
            })
            .await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::QueryResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn patch(
        &self,
        request: tonic::Request<proto::PatchRequest>,
    ) -> Result<tonic::Response<proto::PatchResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .patch(theseus::PatchRequest {
                edit: request
                    .edit
                    .into_iter()
                    .map(edit_from_proto)
                    .collect::<Result<Vec<_>, tonic::Status>>()?,
                write: request.write,
            })
            .await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::PatchResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn coverage(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CoverageReport>, tonic::Status> {
        let outcome = self.0.coverage().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::CoverageReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn implement(
        &self,
        request: tonic::Request<proto::ImplementRequest>,
    ) -> Result<tonic::Response<proto::ImplementResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .implement(theseus::ImplementRequest {
                method: request
                    .method
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `method` is required",
                    ))?,
                body: request
                    .body
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `body` is required",
                    ))?,
                port: request.port,
                adapter: request.adapter,
            })
            .await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::ImplementResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn edit_rust_item(
        &self,
        request: tonic::Request<proto::RustItemRequest>,
    ) -> Result<tonic::Response<proto::RustItemResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .edit_rust_item(theseus::RustItemRequest {
                path: request
                    .path
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `path` is required",
                    ))?,
                revision: request
                    .revision
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `revision` is required",
                    ))?,
                item: request
                    .item
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `item` is required",
                    ))?,
                replace: request.replace,
            })
            .await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::RustItemResult { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn show(
        &self,
        request: tonic::Request<proto::ShowRequest>,
    ) -> Result<tonic::Response<proto::HandlerSource>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .show(theseus::ShowRequest {
                method: request
                    .method
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `method` is required",
                    ))?,
                port: request.port,
                adapter: request.adapter,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::HandlerSource { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn check(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CheckReport>, tonic::Status> {
        let outcome = self.0.check().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::CheckReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn calc(
        &self,
        request: tonic::Request<proto::CalcRequest>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .calc(theseus::CalcRequest {
                op: request
                    .op
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `op` is required",
                    ))?,
                a: request
                    .a
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `a` is required",
                    ))?,
                b: request
                    .b
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `b` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn scaffold(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::GeneratedFiles>, tonic::Status> {
        let outcome = self.0.scaffold().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::GeneratedFiles { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn test(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CheckReport>, tonic::Status> {
        let outcome = self.0.test().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::CheckReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn snapshot(
        &self,
        request: tonic::Request<proto::SnapshotRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .snapshot(theseus::SnapshotRequest {
                label: request
                    .label
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `label` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn rollback(
        &self,
        request: tonic::Request<proto::SnapshotRef>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .rollback(theseus::SnapshotRef {
                reference: request
                    .reference
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `reference` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn release(
        &self,
        request: tonic::Request<proto::SnapshotRef>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .release(theseus::SnapshotRef {
                reference: request
                    .reference
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `reference` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn prune(
        &self,
        request: tonic::Request<proto::SnapshotRetention>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .prune(theseus::SnapshotRetention {
                keep: request
                    .keep
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `keep` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn diff(
        &self,
        request: tonic::Request<proto::SnapshotRef>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .diff(theseus::SnapshotRef {
                reference: request
                    .reference
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `reference` is required",
                    ))?,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn restart(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::Empty>, tonic::Status> {
        let outcome = self.0.restart().await;
        match outcome {
            Ok(_) => Ok(tonic::Response::new(proto::Empty {})),
            Err(error) => Err(status(&error)),
        }
    }

    async fn read(
        &self,
        request: tonic::Request<proto::ReadRequest>,
    ) -> Result<tonic::Response<proto::SourceDocument>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .read(theseus::ReadRequest {
                path: request
                    .path
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `path` is required",
                    ))?,
                outline: request.outline,
            })
            .await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::SourceDocument { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn search(
        &self,
        request: tonic::Request<proto::SearchRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .search(theseus::SearchRequest {
                pattern: request
                    .pattern
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `pattern` is required",
                    ))?,
                path: request.path,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn list(
        &self,
        request: tonic::Request<proto::ListRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .list(theseus::ListRequest {
                path: request.path,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn lint(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::CheckReport>, tonic::Status> {
        let outcome = self.0.lint().await;
        match outcome {
            Ok(value) => {
                match serde_json::to_string(&value) {
                    Ok(json) => Ok(tonic::Response::new(proto::CheckReport { json })),
                    Err(error) => Err(tonic::Status::internal(error.to_string())),
                }
            }
            Err(error) => Err(status(&error)),
        }
    }

    async fn drive(
        &self,
        request: tonic::Request<proto::DriveRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .drive(theseus::DriveRequest {
                operation: request
                    .operation
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `operation` is required",
                    ))?,
                input: request.input,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn skills(
        &self,
        request: tonic::Request<proto::SkillsRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .skills(theseus::SkillsRequest {
                topic: request.topic,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn explain(
        &self,
        request: tonic::Request<proto::ExplainRequest>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .explain(theseus::ExplainRequest {
                code: request.code,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn ports(
        &self,
        _request: tonic::Request<proto::Empty>,
    ) -> Result<tonic::Response<proto::String>, tonic::Status> {
        let outcome = self.0.ports().await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::String { value })),
            Err(error) => Err(status(&error)),
        }
    }
}

/// Convert the wire's Edit to the contract's, verb by verb.
fn edit_from_proto(value: proto::Edit) -> Result<theseus_modeling::Edit, tonic::Status> {
    match value.verb {
        Some(proto::edit::Verb::Add(data)) => {
            Ok(theseus_modeling::Edit::Add {
                parent: data
                    .parent
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `parent` is required",
                    ))?,
                kind: data
                    .kind
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `kind` is required",
                    ))?,
                name: data
                    .name
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `name` is required",
                    ))?,
                attrs: data.attrs.into_iter().collect(),
            })
        }
        Some(proto::edit::Verb::Remove(data)) => {
            Ok(theseus_modeling::Edit::Remove {
                target: data
                    .target
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `target` is required",
                    ))?,
            })
        }
        Some(proto::edit::Verb::Rename(data)) => {
            Ok(theseus_modeling::Edit::Rename {
                target: data
                    .target
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `target` is required",
                    ))?,
                to: data
                    .to
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `to` is required",
                    ))?,
            })
        }
        Some(proto::edit::Verb::Set(data)) => {
            Ok(theseus_modeling::Edit::Set {
                target: data
                    .target
                    .ok_or_else(|| tonic::Status::invalid_argument(
                        "field `target` is required",
                    ))?,
                attrs: data.attrs.into_iter().collect(),
            })
        }
        None => Err(tonic::Status::invalid_argument("a Edit carries one verb")),
    }
}

/// The status an operation error maps to, read from the error's type: an
/// operation on its trait default is UNIMPLEMENTED, a write the gate refused
/// is PERMISSION_DENIED, and anything else is INTERNAL.
fn status(error: &anyhow::Error) -> tonic::Status {
    if error.downcast_ref::<theseus::Unimplemented>().is_some() {
        tonic::Status::unimplemented(error.to_string())
    } else if error.downcast_ref::<theseus::Refused>().is_some() {
        tonic::Status::permission_denied(error.to_string())
    } else {
        tonic::Status::internal(error.to_string())
    }
}
