// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract, the outbound port traits and composition root.

/// Writes generated files into the workspace.
pub trait Workspace {
    /// Write one generated file to disk.
    fn write_file(
        &self,
        request: &theseus_modeling::GeneratedFile,
    ) -> anyhow::Result<()>;
}

/// Composition root: the model plus the wired outbound ports.
pub struct Ctx<'a> {
    pub model: &'a theseus_modeling::Model,
    pub workspace: &'a dyn Workspace,
    pub calculator: &'a dyn theseus_calculator::CalculatorService,
}

/// The `QueryRequest` request.
#[derive(Debug, Clone)]
pub struct QueryRequest {
    /// Filter handles by a substring of handle, name, kind, or summary.
    pub find: Option<String>,
    /// Narrow to one element by its exact handle.
    pub node: Option<String>,
    /// Keep only handles of this element kind (operation, type, or port).
    pub kind: Option<String>,
}

/// The `PatchRequest` request.
#[derive(Debug, Clone)]
pub struct PatchRequest {
    /// A pipe-separated edit `verb|target|key=value...`, repeatable, applied in order.
    pub edit: Vec<String>,
    /// Apply the edit by reprojecting the model.
    pub write: bool,
}

/// The `ImplementRequest` request.
#[derive(Debug, Clone)]
pub struct ImplementRequest {
    /// Name of the operation to implement.
    pub method: String,
    /// The handler body to splice into the impl.
    pub body: String,
}

/// The `ShowRequest` request.
#[derive(Debug, Clone)]
pub struct ShowRequest {
    /// Name of the operation whose handler to show.
    pub method: String,
}

/// The `CalcRequest` request.
#[derive(Debug, Clone)]
pub struct CalcRequest {
    /// The operator: add, subtract, multiply, or divide.
    pub op: String,
    /// Left operand.
    pub a: f64,
    /// Right operand.
    pub b: f64,
}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
pub trait TheseusService {
    /// Print Theseus's model of itself as JSON.
    fn model(&self) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: model")
    }

    /// Check that the workspace conforms to its self-model.
    fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        anyhow::bail!("unimplemented operation: verify")
    }

    /// Regenerate model-derived code from the self-model.
    fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        anyhow::bail!("unimplemented operation: generate")
    }

    /// Return a stable handle and model hash for a model element.
    fn query(
        &self,
        _request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        anyhow::bail!("unimplemented operation: query")
    }

    /// Propose an edit to the model.
    fn patch(
        &self,
        _request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        anyhow::bail!("unimplemented operation: patch")
    }

    /// Report which operations have an authored handler.
    fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        anyhow::bail!("unimplemented operation: coverage")
    }

    /// Splice an authored handler for an unimplemented operation.
    fn implement(&self, _request: ImplementRequest) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: implement")
    }

    /// Show an operation's current handler source.
    fn show(&self, _request: ShowRequest) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: show")
    }

    /// Evaluate an arithmetic expression through the calculator service.
    fn calc(&self, _request: CalcRequest) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: calc")
    }

    /// Write the skeleton of each library service crate that is missing it.
    fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        anyhow::bail!("unimplemented operation: scaffold")
    }
}
