// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract, the outbound port traits and composition roots, the agent tool catalog and dispatch.

/// Writes generated files into the workspace.
#[async_trait::async_trait]
pub trait Workspace: Send + Sync {
    /// Acquire the repository write lease and open a recoverable mutation after checking the expected generated revision.
    async fn begin_mutation(
        &self,
        _request: &theseus::ExpectedFileSet,
    ) -> anyhow::Result<theseus::PendingMutation> {
        Err(Unimplemented("workspace.begin_mutation").into())
    }
}

/// A borrowed adapter serves the port its target serves, so a wrapper
/// generic over the port holds a borrow as readily as an owned adapter.
#[async_trait::async_trait]
impl<T: Workspace + ?Sized> Workspace for &T {
    async fn begin_mutation(
        &self,
        request: &theseus::ExpectedFileSet,
    ) -> anyhow::Result<theseus::PendingMutation> {
        (**self).begin_mutation(request).await
    }
}

/// Checkpoints and restores the working tree.
#[async_trait::async_trait]
pub trait Checkpoint: Send + Sync {
    /// Checkpoint tracked files and exact model-owned working-tree state.
    async fn snapshot(
        &self,
        _request: &theseus::CheckpointSnapshotRequest,
    ) -> anyhow::Result<theseus::CheckpointSnapshot> {
        Err(Unimplemented("checkpoint.snapshot").into())
    }

    /// Restore tracked files and exact model-owned working-tree state from a snapshot.
    async fn restore(
        &self,
        _request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<theseus::CheckpointRestore> {
        Err(Unimplemented("checkpoint.restore").into())
    }

    /// Return a bounded, escaped Git-style diff with exact mode records against the given snapshot.
    async fn diff(
        &self,
        _request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<String> {
        Err(Unimplemented("checkpoint.diff").into())
    }

    /// Release a snapshot that is no longer needed.
    async fn release(&self, _request: &str) -> anyhow::Result<String> {
        Err(Unimplemented("checkpoint.release").into())
    }

    /// Release older snapshots beyond a retention limit.
    async fn prune(&self, _request: &SnapshotRetention) -> anyhow::Result<String> {
        Err(Unimplemented("checkpoint.prune").into())
    }
}

/// A borrowed adapter serves the port its target serves, so a wrapper
/// generic over the port holds a borrow as readily as an owned adapter.
#[async_trait::async_trait]
impl<T: Checkpoint + ?Sized> Checkpoint for &T {
    async fn snapshot(
        &self,
        request: &theseus::CheckpointSnapshotRequest,
    ) -> anyhow::Result<theseus::CheckpointSnapshot> {
        (**self).snapshot(request).await
    }

    async fn restore(
        &self,
        request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<theseus::CheckpointRestore> {
        (**self).restore(request).await
    }

    async fn diff(
        &self,
        request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<String> {
        (**self).diff(request).await
    }

    async fn release(&self, request: &str) -> anyhow::Result<String> {
        (**self).release(request).await
    }

    async fn prune(&self, request: &SnapshotRetention) -> anyhow::Result<String> {
        (**self).prune(request).await
    }
}

/// Compile-checks the workspace and reports the outcome.
#[async_trait::async_trait]
pub trait Toolchain: Send + Sync {
    /// Compile-check the workspace and report the outcome.
    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("toolchain.check").into())
    }

    /// Compile-check an already leased workspace mutation, allowing its journal to cover lockfile updates.
    async fn check_mutation(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("toolchain.check_mutation").into())
    }

    /// Run the workspace tests and report the outcome.
    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("toolchain.test").into())
    }

    /// Run clippy across the workspace with warnings denied and report the outcome.
    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("toolchain.lint").into())
    }
}

/// A borrowed adapter serves the port its target serves, so a wrapper
/// generic over the port holds a borrow as readily as an owned adapter.
#[async_trait::async_trait]
impl<T: Toolchain + ?Sized> Toolchain for &T {
    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        (**self).check().await
    }

    async fn check_mutation(&self) -> anyhow::Result<theseus::CheckReport> {
        (**self).check_mutation().await
    }

    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        (**self).test().await
    }

    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        (**self).lint().await
    }
}

/// The `workspace` port carrying a write permission: a gated method is refused
/// without it, and an ungated one passes through. It wraps an owned
/// adapter or a borrowed one, the same gate either way.
pub struct GatedWorkspace<A> {
    pub workspace: A,
    pub allow_writes: bool,
}

#[async_trait::async_trait]
impl<A: Workspace> Workspace for GatedWorkspace<A> {
    async fn begin_mutation(
        &self,
        request: &theseus::ExpectedFileSet,
    ) -> anyhow::Result<theseus::PendingMutation> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.workspace.begin_mutation(request).await
    }
}

/// The `checkpoint` port carrying a write permission: a gated method is refused
/// without it, and an ungated one passes through. It wraps an owned
/// adapter or a borrowed one, the same gate either way.
pub struct GatedCheckpoint<A> {
    pub checkpoint: A,
    pub allow_writes: bool,
}

#[async_trait::async_trait]
impl<A: Checkpoint> Checkpoint for GatedCheckpoint<A> {
    async fn snapshot(
        &self,
        request: &theseus::CheckpointSnapshotRequest,
    ) -> anyhow::Result<theseus::CheckpointSnapshot> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.checkpoint.snapshot(request).await
    }

    async fn restore(
        &self,
        request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<theseus::CheckpointRestore> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.checkpoint.restore(request).await
    }

    async fn diff(
        &self,
        request: &theseus::CheckpointStateRequest,
    ) -> anyhow::Result<String> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.checkpoint.diff(request).await
    }

    async fn release(&self, request: &str) -> anyhow::Result<String> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.checkpoint.release(request).await
    }

    async fn prune(&self, request: &SnapshotRetention) -> anyhow::Result<String> {
        if !self.allow_writes {
            return Err(Refused.into());
        }
        self.checkpoint.prune(request).await
    }
}

/// Composition root: the model plus the wired outbound ports.
pub struct Ctx<'a> {
    pub model: &'a theseus_modeling::Model,
    pub workspace: &'a dyn Workspace,
    pub checkpoint: &'a dyn Checkpoint,
    pub calculator: &'a dyn theseus_calculator::CalculatorService,
    pub toolchain: &'a dyn Toolchain,
}

/// The `QueryRequest` request.
#[derive(Debug, Clone)]
pub struct QueryRequest {
    /// Filter handles by a substring of handle, name, kind, or summary.
    pub find: Option<String>,
    /// Narrow to one element by its exact handle.
    pub node: Option<String>,
    /// Keep only handles of this element kind (operation, type, or port).
    pub kind: Option<String>,
}

/// The `PatchRequest` request.
#[derive(Debug, Clone)]
pub struct PatchRequest {
    /// The edits to apply in order, each a verb over a handle from `query`.
    pub edit: Vec<theseus_modeling::Edit>,
    /// When true, apply the edit and reproject the model to disk; when false, validate and preview only.
    pub write: bool,
}

/// The `ImplementRequest` request.
#[derive(Debug, Clone)]
pub struct ImplementRequest {
    /// Name of the operation — or, with `port`, the port method — to implement.
    pub method: String,
    /// The handler body to splice into the impl.
    pub body: String,
    /// Name of the port whose adapter method to implement.
    pub port: Option<String>,
    /// The adapter type to target when the file holds more than one.
    pub adapter: Option<String>,
}

/// The `ShowRequest` request.
#[derive(Debug, Clone)]
pub struct ShowRequest {
    /// Name of the operation — or, with `port`, the port method — to show.
    pub method: String,
    /// Name of the port whose adapter method to show.
    pub port: Option<String>,
    /// The adapter type to target when the file holds more than one.
    pub adapter: Option<String>,
}

/// The `CalcRequest` request.
#[derive(Debug, Clone)]
pub struct CalcRequest {
    /// The operator: add, subtract, multiply, or divide.
    pub op: String,
    /// Left operand.
    pub a: f64,
    /// Right operand.
    pub b: f64,
}

/// The `SnapshotRequest` request.
#[derive(Debug, Clone)]
pub struct SnapshotRequest {
    /// A short label naming the snapshot.
    pub label: String,
}

/// The `SnapshotRef` request.
#[derive(Debug, Clone)]
pub struct SnapshotRef {
    /// The snapshot id, as returned by `snapshot`.
    pub reference: String,
}

/// The `SnapshotRetention` request.
#[derive(Debug, Clone)]
pub struct SnapshotRetention {
    /// Number of newest snapshots to retain.
    pub keep: u32,
}

/// The `ReadRequest` request.
#[derive(Debug, Clone)]
pub struct ReadRequest {
    /// The workspace-relative file to read.
    pub path: String,
}

/// The `SearchRequest` request.
#[derive(Debug, Clone)]
pub struct SearchRequest {
    /// The text to find.
    pub pattern: String,
    /// A workspace-relative subtree to search. The whole workspace when omitted.
    pub path: Option<String>,
}

/// The `ListRequest` request.
#[derive(Debug, Clone)]
pub struct ListRequest {
    /// The workspace-relative directory to list. The root when omitted.
    pub path: Option<String>,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}

/// A write refused by a permission gate. A transport adapter downcasts it
/// to map the refusal in its own vocabulary.
#[derive(Debug)]
pub struct Refused;

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "writes are not permitted; grant write permission to apply this edit")
    }
}

impl std::error::Error for Refused {}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
#[async_trait::async_trait]
pub trait TheseusService: Send + Sync {
    /// Print Theseus's model of itself as JSON.
    async fn model(&self) -> anyhow::Result<String> {
        Err(Unimplemented("model").into())
    }

    /// Check that the workspace conforms to its self-model.
    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        Err(Unimplemented("verify").into())
    }

    /// Regenerate model-derived code from the self-model.
    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        Err(Unimplemented("generate").into())
    }

    /// Return a stable handle and model hash for a model element.
    async fn query(
        &self,
        _request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        Err(Unimplemented("query").into())
    }

    /// Propose an edit to the model.
    async fn patch(
        &self,
        _request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        Err(Unimplemented("patch").into())
    }

    /// Report which operations have no authored handler.
    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        Err(Unimplemented("coverage").into())
    }

    /// Splice an authored handler or adapter method and compile-check it.
    async fn implement(
        &self,
        _request: ImplementRequest,
    ) -> anyhow::Result<theseus::ImplementResult> {
        Err(Unimplemented("implement").into())
    }

    /// Show an operation's current handler source.
    async fn show(&self, _request: ShowRequest) -> anyhow::Result<String> {
        Err(Unimplemented("show").into())
    }

    /// Compile-check the workspace and report the outcome.
    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("check").into())
    }

    /// Evaluate an arithmetic expression through the calculator service.
    async fn calc(&self, _request: CalcRequest) -> anyhow::Result<String> {
        Err(Unimplemented("calc").into())
    }

    /// Write the skeleton of each library service crate that is missing it.
    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        Err(Unimplemented("scaffold").into())
    }

    /// Run the workspace tests and report the outcome.
    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("test").into())
    }

    /// Checkpoint tracked files and exact model-owned working-tree state, and return the snapshot id.
    async fn snapshot(&self, _request: SnapshotRequest) -> anyhow::Result<String> {
        Err(Unimplemented("snapshot").into())
    }

    /// Restore tracked files and exact model-owned working-tree state from a snapshot.
    async fn rollback(&self, _request: SnapshotRef) -> anyhow::Result<String> {
        Err(Unimplemented("rollback").into())
    }

    /// Release a snapshot that is no longer needed.
    async fn release(&self, _request: SnapshotRef) -> anyhow::Result<String> {
        Err(Unimplemented("release").into())
    }

    /// Release older snapshots beyond a retention limit.
    async fn prune(&self, _request: SnapshotRetention) -> anyhow::Result<String> {
        Err(Unimplemented("prune").into())
    }

    /// Show what changed in the working tree since a snapshot.
    async fn diff(&self, _request: SnapshotRef) -> anyhow::Result<String> {
        Err(Unimplemented("diff").into())
    }

    /// Compile-check readiness for an inbound-managed process restart.
    async fn restart(&self) -> anyhow::Result<()> {
        Err(Unimplemented("restart").into())
    }

    /// Read a workspace file, capped for a tool result.
    async fn read(&self, _request: ReadRequest) -> anyhow::Result<String> {
        Err(Unimplemented("read").into())
    }

    /// Find a pattern's occurrences across the workspace.
    async fn search(&self, _request: SearchRequest) -> anyhow::Result<String> {
        Err(Unimplemented("search").into())
    }

    /// List a workspace directory.
    async fn list(&self, _request: ListRequest) -> anyhow::Result<String> {
        Err(Unimplemented("list").into())
    }

    /// Run clippy across the workspace with warnings denied.
    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        Err(Unimplemented("lint").into())
    }
}

/// An owned composition root: the service over one owned adapter per port,
/// driven through a fresh borrowed `Ctx` per call. A long-lived inbound
/// holds it where a borrowed root cannot live.
pub struct Standalone<
    WorkspaceAdapter: Workspace,
    CheckpointAdapter: Checkpoint,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> {
    pub model: theseus_modeling::Model,
    pub workspace: WorkspaceAdapter,
    pub checkpoint: CheckpointAdapter,
    pub calculator: CalculatorAdapter,
    pub toolchain: ToolchainAdapter,
}

impl<
    WorkspaceAdapter: Workspace,
    CheckpointAdapter: Checkpoint,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> Standalone<WorkspaceAdapter, CheckpointAdapter, CalculatorAdapter, ToolchainAdapter> {
    /// The borrowed composition root one call runs over.
    fn ctx(&self) -> Ctx<'_> {
        Ctx {
            model: &self.model,
            workspace: &self.workspace,
            checkpoint: &self.checkpoint,
            calculator: &self.calculator,
            toolchain: &self.toolchain,
        }
    }
}

#[async_trait::async_trait]
impl<
    WorkspaceAdapter: Workspace,
    CheckpointAdapter: Checkpoint,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> TheseusService
for Standalone<
    WorkspaceAdapter,
    CheckpointAdapter,
    CalculatorAdapter,
    ToolchainAdapter,
> {
    async fn model(&self) -> anyhow::Result<String> {
        self.ctx().model().await
    }

    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        self.ctx().verify().await
    }

    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        self.ctx().generate().await
    }

    async fn query(
        &self,
        request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        self.ctx().query(request).await
    }

    async fn patch(
        &self,
        request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        self.ctx().patch(request).await
    }

    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        self.ctx().coverage().await
    }

    async fn implement(
        &self,
        request: ImplementRequest,
    ) -> anyhow::Result<theseus::ImplementResult> {
        self.ctx().implement(request).await
    }

    async fn show(&self, request: ShowRequest) -> anyhow::Result<String> {
        self.ctx().show(request).await
    }

    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        self.ctx().check().await
    }

    async fn calc(&self, request: CalcRequest) -> anyhow::Result<String> {
        self.ctx().calc(request).await
    }

    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        self.ctx().scaffold().await
    }

    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        self.ctx().test().await
    }

    async fn snapshot(&self, request: SnapshotRequest) -> anyhow::Result<String> {
        self.ctx().snapshot(request).await
    }

    async fn rollback(&self, request: SnapshotRef) -> anyhow::Result<String> {
        self.ctx().rollback(request).await
    }

    async fn release(&self, request: SnapshotRef) -> anyhow::Result<String> {
        self.ctx().release(request).await
    }

    async fn prune(&self, request: SnapshotRetention) -> anyhow::Result<String> {
        self.ctx().prune(request).await
    }

    async fn diff(&self, request: SnapshotRef) -> anyhow::Result<String> {
        self.ctx().diff(request).await
    }

    async fn restart(&self) -> anyhow::Result<()> {
        self.ctx().restart().await
    }

    async fn read(&self, request: ReadRequest) -> anyhow::Result<String> {
        self.ctx().read(request).await
    }

    async fn search(&self, request: SearchRequest) -> anyhow::Result<String> {
        self.ctx().search(request).await
    }

    async fn list(&self, request: ListRequest) -> anyhow::Result<String> {
        self.ctx().list(request).await
    }

    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        self.ctx().lint().await
    }
}

/// Theseus's agent tool catalog, one tool-use definition per exposed
/// operation. Served by the agent loop and the MCP server alike.
pub fn tool_catalog() -> Vec<serde_json::Value> {
    vec![
        serde_json::json!({ "name" : "model", "description" :
        "Return Theseus's model of itself as JSON.", "input_schema" : { "type" :
        "object", "properties" : {} } }), serde_json::json!({ "name" : "verify",
        "description" : "Check that the workspace conforms to the model.", "input_schema"
        : { "type" : "object", "properties" : {} } }), serde_json::json!({ "name" :
        "generate", "description" :
        "Regenerate model-derived code (generated.rs files) from the self-model. Call this after scaffolding a new service crate so generated.rs exists before authoring handlers.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "query", "description" :
        "List model element handles, optionally filtered by `find` (a substring), `node` (an exact handle), or `kind`.",
        "input_schema" : { "type" : "object", "properties" : { "find" : { "type" :
        "string" }, "node" : { "type" : "string" }, "kind" : { "type" : "string" } } }
        }), serde_json::json!({ "name" : "patch", "description" :
        "Edit the model. Each edit names a handle from `query`; a top-level node attaches to the model root, `model:<model>`. An operation's `tool` attribute is its agent tool description — an operation carrying one joins this tool catalog at the next rebuild. An operation's `uses` attribute declares the ports its handler reaches, comma-separated — `verify` holds the authored handler to exactly these. `write` true reprojects under a repository transaction and compile gate; a failed check restores the prior files.",
        "input_schema" : { "type" : "object", "properties" : { "edit" : { "type" :
        "array", "items" : { "oneOf" : [{ "type" : "object", "properties" : { "verb" : {
        "const" : "add" }, "parent" : { "type" : "string" }, "kind" : { "type" : "string"
        }, "name" : { "type" : "string" }, "attrs" : { "type" : "object",
        "additionalProperties" : { "type" : "string" } } }, "required" : ["verb",
        "parent", "kind", "name"] }, { "type" : "object", "properties" : { "verb" : {
        "const" : "remove" }, "target" : { "type" : "string" } }, "required" : ["verb",
        "target"] }, { "type" : "object", "properties" : { "verb" : { "const" : "rename"
        }, "target" : { "type" : "string" }, "to" : { "type" : "string" } }, "required" :
        ["verb", "target", "to"] }, { "type" : "object", "properties" : { "verb" : {
        "const" : "set" }, "target" : { "type" : "string" }, "attrs" : { "type" :
        "object", "additionalProperties" : { "type" : "string" } } }, "required" :
        ["verb", "target", "attrs"] }] } }, "write" : { "type" : "boolean" } },
        "required" : ["edit"] } }), serde_json::json!({ "name" : "coverage",
        "description" : "Report which operations have no authored handler.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "implement", "description" :
        "Write a handler for an operation into the service impl, so a newly-added operation stops being unimplemented. `method` is the operation name. `body` is the Rust handler body — the statements inside the generated `fn <method>(&self, request: <Request>) -> anyhow::Result<<Response>>`, which the splice wraps for you. With `port`, `method` names one of that port's methods instead, and the body lands in the port's adapter impl in the crate's authored adapters file — `adapter` picks the implementing type when the file holds more than one. The write is followed by a compile check, and the result carries its outcome — on a failure, fix the body and implement again, which replaces the method in place. Author it after `patch` adds the operation or method (use `show` to read the signature), then `verify`. Example: `{ \"method\": \"greet\", \"body\": \"Ok(\\\"hello\\\".to_string())\" }`.",
        "input_schema" : { "type" : "object", "properties" : { "method" : { "type" :
        "string" }, "body" : { "type" : "string" }, "port" : { "type" : "string" },
        "adapter" : { "type" : "string" } }, "required" : ["method", "body"] } }),
        serde_json::json!({ "name" : "show", "description" :
        "Show the current authored handler source for an operation. `method` is an operation name from `query` (kind `operation`). With `port`, `method` names one of that port's methods and the adapter method shows instead — `adapter` picks the implementing type when the file holds more than one. For a method with no authored source yet, it returns the generated signature, so you can read the request and response types before authoring. Example: `{ \"method\": \"verify\" }`.",
        "input_schema" : { "type" : "object", "properties" : { "method" : { "type" :
        "string" }, "port" : { "type" : "string" }, "adapter" : { "type" : "string" } },
        "required" : ["method"] } }), serde_json::json!({ "name" : "check", "description"
        :
        "Compile-check the workspace and report the outcome. `implement` runs it after each write on its own. Call it directly after a `patch` that writes, or to prove the tree compiles before a rebuild.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "scaffold", "description" :
        "Scaffold missing library service crates under a repository transaction and compile gate. A failed check restores the prior files and removes only paths the transaction created.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "test", "description" :
        "Run the workspace tests and report the outcome. Slower than check; use it when behavior matters.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "snapshot", "description" :
        "Checkpoint tracked files and the exact present or absent state of paths owned by the current persisted model before risky edits. Returns a snapshot id for rollback. Requires write permission.",
        "input_schema" : { "type" : "object", "properties" : { "label" : { "type" :
        "string" } }, "required" : ["label"] } }), serde_json::json!({ "name" :
        "rollback", "description" :
        "Restore tracked files and the exact present or absent state of model-owned paths from a snapshot, leaving unrelated untracked files untouched. Requires write permission.",
        "input_schema" : { "type" : "object", "properties" : { "reference" : { "type" :
        "string" } }, "required" : ["reference"] } }), serde_json::json!({ "name" :
        "release", "description" :
        "Release a snapshot by atomically deleting its validated pair of private Git refs. Requires write permission.",
        "input_schema" : { "type" : "object", "properties" : { "reference" : { "type" :
        "string" } }, "required" : ["reference"] } }), serde_json::json!({ "name" :
        "prune", "description" :
        "Release older snapshot refs, retaining only the requested number of newest snapshots. Requires write permission.",
        "input_schema" : { "type" : "object", "properties" : { "keep" : { "type" :
        "number" } }, "required" : ["keep"] } }), serde_json::json!({ "name" : "diff",
        "description" :
        "Show what changed in the working tree since a snapshot. `reference` is the snapshot id returned by `snapshot`. Returns a bounded, escaped Git-style diff with exact mode records, or an empty string when nothing has changed. Requires write permission.",
        "input_schema" : { "type" : "object", "properties" : { "reference" : { "type" :
        "string" } }, "required" : ["reference"] } }), serde_json::json!({ "name" :
        "restart", "description" :
        "Compile-check readiness for process replacement. The agent inbound uses success to rebuild and resume this session in the new binary; other inbounds must arrange their own rebuild and replacement. Apply the edits first — `patch` with write true, `implement` each handler, `check` — then call this alone, with no other tool in the turn.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "read", "description" :
        "Read a file from the workspace. `path` is workspace-relative, e.g. `rust/theseus/src/lib.rs`. The result is capped, so `search` first to find the right spot. Prefer `show` for an operation's handler or an adapter method — `read` reaches everything else: authored composition roots, generated files, manifests, docs. Example: { \"path\": \"README.md\" }.",
        "input_schema" : { "type" : "object", "properties" : { "path" : { "type" :
        "string" } }, "required" : ["path"] } }), serde_json::json!({ "name" : "search",
        "description" :
        "Search the workspace for lines containing `pattern`, reported as path:line: text, capped. `path` narrows the search to a subtree, e.g. `rust/agent`. Use it to find house patterns and neighbors before authoring, then `read` the file. Example: { \"pattern\": \"impl Toolchain\", \"path\": \"rust/theseus\" }.",
        "input_schema" : { "type" : "object", "properties" : { "pattern" : { "type" :
        "string" }, "path" : { "type" : "string" } }, "required" : ["pattern"] } }),
        serde_json::json!({ "name" : "list", "description" :
        "List a workspace directory's entries, directories marked with a trailing `/`. `path` is workspace-relative; omit it for the workspace root. Example: { \"path\": \"rust\" }.",
        "input_schema" : { "type" : "object", "properties" : { "path" : { "type" :
        "string" } } } }), serde_json::json!({ "name" : "lint", "description" :
        "Run clippy across the workspace with warnings denied and report the outcome.",
        "input_schema" : { "type" : "object", "properties" : {} } })
    ]
}
pub(crate) fn parse_query_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<QueryRequest> {
    Ok(QueryRequest {
        find: serde_json::from_value(
                input.get("find").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `find` field is invalid: {error}"))?,
        node: serde_json::from_value(
                input.get("node").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `node` field is invalid: {error}"))?,
        kind: serde_json::from_value(
                input.get("kind").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `kind` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_patch_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<PatchRequest> {
    Ok(PatchRequest {
        edit: match input.get("edit") {
            None => Default::default(),
            Some(value) => {
                serde_json::from_value(value.clone())
                    .map_err(|error| {
                        anyhow::anyhow!("the `edit` field is invalid: {error}")
                    })?
            }
        },
        write: input
            .get("write")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or_default(),
    })
}
pub(crate) fn parse_implement_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ImplementRequest> {
    Ok(ImplementRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        body: input
            .get("body")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `body`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_show_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ShowRequest> {
    Ok(ShowRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_snapshot_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<SnapshotRequest> {
    Ok(SnapshotRequest {
        label: input
            .get("label")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `label`"))?,
    })
}
pub(crate) fn parse_snapshot_ref_input(
    input: &serde_json::Value,
) -> anyhow::Result<SnapshotRef> {
    Ok(SnapshotRef {
        reference: input
            .get("reference")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `reference`"))?,
    })
}
pub(crate) fn parse_snapshot_retention_input(
    input: &serde_json::Value,
) -> anyhow::Result<SnapshotRetention> {
    Ok(SnapshotRetention {
        keep: serde_json::from_value(
                input.get("keep").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `keep` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_read_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ReadRequest> {
    Ok(ReadRequest {
        path: input
            .get("path")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `path`"))?,
    })
}
pub(crate) fn parse_search_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<SearchRequest> {
    Ok(SearchRequest {
        pattern: input
            .get("pattern")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `pattern`"))?,
        path: serde_json::from_value(
                input.get("path").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `path` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_list_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ListRequest> {
    Ok(ListRequest {
        path: serde_json::from_value(
                input.get("path").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `path` field is invalid: {error}"))?,
    })
}

/// Dispatch one tool call to the service: parse the request from the
/// call's JSON input, run the operation, and render the result — text
/// for a string, otherwise JSON. The catalog and this dispatch render
/// from the same contract, so every catalog entry has an arm here.
pub async fn dispatch_tool(
    service: &impl TheseusService,
    name: &str,
    input: &serde_json::Value,
) -> anyhow::Result<String> {
    match name {
        "model" => Ok(service.model().await?),
        "verify" => Ok(serde_json::to_string(&service.verify().await?)?),
        "generate" => Ok(serde_json::to_string(&service.generate().await?)?),
        "query" => {
            Ok(
                serde_json::to_string(
                    &service.query(parse_query_request_input(input)?).await?,
                )?,
            )
        }
        "patch" => {
            Ok(
                serde_json::to_string(
                    &service.patch(parse_patch_request_input(input)?).await?,
                )?,
            )
        }
        "coverage" => Ok(serde_json::to_string(&service.coverage().await?)?),
        "implement" => {
            Ok(
                serde_json::to_string(
                    &service.implement(parse_implement_request_input(input)?).await?,
                )?,
            )
        }
        "show" => Ok(service.show(parse_show_request_input(input)?).await?),
        "check" => Ok(serde_json::to_string(&service.check().await?)?),
        "scaffold" => Ok(serde_json::to_string(&service.scaffold().await?)?),
        "test" => Ok(serde_json::to_string(&service.test().await?)?),
        "snapshot" => Ok(service.snapshot(parse_snapshot_request_input(input)?).await?),
        "rollback" => Ok(service.rollback(parse_snapshot_ref_input(input)?).await?),
        "release" => Ok(service.release(parse_snapshot_ref_input(input)?).await?),
        "prune" => Ok(service.prune(parse_snapshot_retention_input(input)?).await?),
        "diff" => Ok(service.diff(parse_snapshot_ref_input(input)?).await?),
        "restart" => Ok(serde_json::to_string(&service.restart().await?)?),
        "read" => Ok(service.read(parse_read_request_input(input)?).await?),
        "search" => Ok(service.search(parse_search_request_input(input)?).await?),
        "list" => Ok(service.list(parse_list_request_input(input)?).await?),
        "lint" => Ok(serde_json::to_string(&service.lint().await?)?),
        other => {
            anyhow::bail!(
                "unknown tool `{other}`; tools are model, verify, generate, query, patch, coverage, implement, show, check, scaffold, test, snapshot, rollback, release, prune, diff, restart, read, search, list, lint"
            )
        }
    }
}
