// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract, the outbound port traits and composition roots, the agent tool catalog and dispatch.

/// Writes generated files into the workspace.
#[async_trait::async_trait]
pub trait Workspace: Send + Sync {
    /// Write one generated file to disk.
    async fn write_file(
        &self,
        _request: &theseus_modeling::GeneratedFile,
    ) -> anyhow::Result<()> {
        Err(Unimplemented("workspace.write_file").into())
    }
}

/// Compile-checks the workspace and reports the outcome.
#[async_trait::async_trait]
pub trait Toolchain: Send + Sync {
    /// Compile-check the workspace and report the outcome.
    async fn check(&self) -> anyhow::Result<String> {
        Err(Unimplemented("toolchain.check").into())
    }

    /// Run the workspace tests and report the outcome.
    async fn test(&self) -> anyhow::Result<String> {
        Err(Unimplemented("toolchain.test").into())
    }
}

/// Composition root: the model plus the wired outbound ports.
pub struct Ctx<'a> {
    pub model: &'a theseus_modeling::Model,
    pub workspace: &'a dyn Workspace,
    pub calculator: &'a dyn theseus_calculator::CalculatorService,
    pub toolchain: &'a dyn Toolchain,
}

/// The `QueryRequest` request.
#[derive(Debug, Clone)]
pub struct QueryRequest {
    /// Filter handles by a substring of handle, name, kind, or summary.
    pub find: Option<String>,
    /// Narrow to one element by its exact handle.
    pub node: Option<String>,
    /// Keep only handles of this element kind (operation, type, or port).
    pub kind: Option<String>,
}

/// The `PatchRequest` request.
#[derive(Debug, Clone)]
pub struct PatchRequest {
    /// The edits to apply in order, each a verb over a handle from `query`.
    pub edit: Vec<theseus_modeling::Edit>,
    /// Apply the edit by reprojecting the model.
    pub write: bool,
}

/// The `ImplementRequest` request.
#[derive(Debug, Clone)]
pub struct ImplementRequest {
    /// Name of the operation — or, with `port`, the port method — to implement.
    pub method: String,
    /// The handler body to splice into the impl.
    pub body: String,
    /// Name of the port whose adapter method to implement.
    pub port: Option<String>,
    /// The adapter type to target when the file holds more than one.
    pub adapter: Option<String>,
}

/// The `ShowRequest` request.
#[derive(Debug, Clone)]
pub struct ShowRequest {
    /// Name of the operation — or, with `port`, the port method — to show.
    pub method: String,
    /// Name of the port whose adapter method to show.
    pub port: Option<String>,
    /// The adapter type to target when the file holds more than one.
    pub adapter: Option<String>,
}

/// The `CalcRequest` request.
#[derive(Debug, Clone)]
pub struct CalcRequest {
    /// The operator: add, subtract, multiply, or divide.
    pub op: String,
    /// Left operand.
    pub a: f64,
    /// Right operand.
    pub b: f64,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}

/// A write refused by a permission gate. A transport adapter downcasts it
/// to map the refusal in its own vocabulary.
#[derive(Debug)]
pub struct Refused;

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "writes are not permitted; grant write permission to apply this edit")
    }
}

impl std::error::Error for Refused {}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
#[async_trait::async_trait]
pub trait TheseusService: Send + Sync {
    /// Print Theseus's model of itself as JSON.
    async fn model(&self) -> anyhow::Result<String> {
        Err(Unimplemented("model").into())
    }

    /// Check that the workspace conforms to its self-model.
    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        Err(Unimplemented("verify").into())
    }

    /// Regenerate model-derived code from the self-model.
    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        Err(Unimplemented("generate").into())
    }

    /// Return a stable handle and model hash for a model element.
    async fn query(
        &self,
        _request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        Err(Unimplemented("query").into())
    }

    /// Propose an edit to the model.
    async fn patch(
        &self,
        _request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        Err(Unimplemented("patch").into())
    }

    /// Report which operations have an authored handler.
    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        Err(Unimplemented("coverage").into())
    }

    /// Splice an authored handler or adapter method and compile-check it.
    async fn implement(&self, _request: ImplementRequest) -> anyhow::Result<String> {
        Err(Unimplemented("implement").into())
    }

    /// Show an operation's current handler source.
    async fn show(&self, _request: ShowRequest) -> anyhow::Result<String> {
        Err(Unimplemented("show").into())
    }

    /// Compile-check the workspace and report the outcome.
    async fn check(&self) -> anyhow::Result<String> {
        Err(Unimplemented("check").into())
    }

    /// Evaluate an arithmetic expression through the calculator service.
    async fn calc(&self, _request: CalcRequest) -> anyhow::Result<String> {
        Err(Unimplemented("calc").into())
    }

    /// Write the skeleton of each library service crate that is missing it.
    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        Err(Unimplemented("scaffold").into())
    }

    /// Run the workspace tests and report the outcome.
    async fn test(&self) -> anyhow::Result<String> {
        Err(Unimplemented("test").into())
    }
}

/// An owned composition root: the service over one owned adapter per port,
/// driven through a fresh borrowed `Ctx` per call. A long-lived inbound
/// holds it where a borrowed root cannot live.
pub struct Standalone<
    WorkspaceAdapter: Workspace,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> {
    pub model: theseus_modeling::Model,
    pub workspace: WorkspaceAdapter,
    pub calculator: CalculatorAdapter,
    pub toolchain: ToolchainAdapter,
}

impl<
    WorkspaceAdapter: Workspace,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> Standalone<WorkspaceAdapter, CalculatorAdapter, ToolchainAdapter> {
    /// The borrowed composition root one call runs over.
    fn ctx(&self) -> Ctx<'_> {
        Ctx {
            model: &self.model,
            workspace: &self.workspace,
            calculator: &self.calculator,
            toolchain: &self.toolchain,
        }
    }
}

#[async_trait::async_trait]
impl<
    WorkspaceAdapter: Workspace,
    CalculatorAdapter: theseus_calculator::CalculatorService,
    ToolchainAdapter: Toolchain,
> TheseusService for Standalone<WorkspaceAdapter, CalculatorAdapter, ToolchainAdapter> {
    async fn model(&self) -> anyhow::Result<String> {
        self.ctx().model().await
    }

    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        self.ctx().verify().await
    }

    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        self.ctx().generate().await
    }

    async fn query(
        &self,
        request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        self.ctx().query(request).await
    }

    async fn patch(
        &self,
        request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        self.ctx().patch(request).await
    }

    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        self.ctx().coverage().await
    }

    async fn implement(&self, request: ImplementRequest) -> anyhow::Result<String> {
        self.ctx().implement(request).await
    }

    async fn show(&self, request: ShowRequest) -> anyhow::Result<String> {
        self.ctx().show(request).await
    }

    async fn check(&self) -> anyhow::Result<String> {
        self.ctx().check().await
    }

    async fn calc(&self, request: CalcRequest) -> anyhow::Result<String> {
        self.ctx().calc(request).await
    }

    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        self.ctx().scaffold().await
    }

    async fn test(&self) -> anyhow::Result<String> {
        self.ctx().test().await
    }
}

/// Theseus's agent tool catalog, one tool-use definition per exposed
/// operation. Served by the agent loop and the MCP server alike.
pub fn tool_catalog() -> Vec<serde_json::Value> {
    vec![
        serde_json::json!({ "name" : "model", "description" :
        "Return Theseus's model of itself as JSON.", "input_schema" : { "type" :
        "object", "properties" : {} } }), serde_json::json!({ "name" : "verify",
        "description" : "Check that the workspace conforms to the model.", "input_schema"
        : { "type" : "object", "properties" : {} } }), serde_json::json!({ "name" :
        "query", "description" :
        "List model element handles, optionally filtered by `find` (a substring), `node` (an exact handle), or `kind`.",
        "input_schema" : { "type" : "object", "properties" : { "find" : { "type" :
        "string" }, "node" : { "type" : "string" }, "kind" : { "type" : "string" } } }
        }), serde_json::json!({ "name" : "patch", "description" :
        "Edit the model. Each edit names a handle from `query`; a top-level node attaches to the model root, `model:<model>`. An operation's `tool` attribute is its agent tool description — an operation carrying one joins this tool catalog at the next rebuild. An operation's `uses` attribute declares the ports its handler reaches, comma-separated — `verify` holds the authored handler to exactly these. `write` true reprojects to disk.",
        "input_schema" : { "type" : "object", "properties" : { "edit" : { "type" :
        "array", "items" : { "oneOf" : [{ "type" : "object", "properties" : { "verb" : {
        "const" : "add" }, "parent" : { "type" : "string" }, "kind" : { "type" : "string"
        }, "name" : { "type" : "string" }, "attrs" : { "type" : "object",
        "additionalProperties" : { "type" : "string" } } }, "required" : ["verb",
        "parent", "kind", "name"] }, { "type" : "object", "properties" : { "verb" : {
        "const" : "remove" }, "target" : { "type" : "string" } }, "required" : ["verb",
        "target"] }, { "type" : "object", "properties" : { "verb" : { "const" : "rename"
        }, "target" : { "type" : "string" }, "to" : { "type" : "string" } }, "required" :
        ["verb", "target", "to"] }, { "type" : "object", "properties" : { "verb" : {
        "const" : "set" }, "target" : { "type" : "string" }, "attrs" : { "type" :
        "object", "additionalProperties" : { "type" : "string" } } }, "required" :
        ["verb", "target", "attrs"] }] } }, "write" : { "type" : "boolean" } },
        "required" : ["edit"] } }), serde_json::json!({ "name" : "coverage",
        "description" : "Report which operations have no authored handler.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "implement", "description" :
        "Write a handler for an operation into the service impl, so a newly-added operation stops being unimplemented. `method` is the operation name. `body` is the Rust handler body — the statements inside the generated `fn <method>(&self, request: <Request>) -> anyhow::Result<<Response>>`, which the splice wraps for you. With `port`, `method` names one of that port's methods instead, and the body lands in the port's adapter impl in the crate's authored adapters file — `adapter` picks the implementing type when the file holds more than one. The write is followed by a compile check, and the result carries its outcome — on a failure, fix the body and implement again, which replaces the method in place. Author it after `patch` adds the operation or method (use `show` to read the signature), then `verify`. Example: `{ \"method\": \"greet\", \"body\": \"Ok(\\\"hello\\\".to_string())\" }`.",
        "input_schema" : { "type" : "object", "properties" : { "method" : { "type" :
        "string" }, "body" : { "type" : "string" }, "port" : { "type" : "string" },
        "adapter" : { "type" : "string" } }, "required" : ["method", "body"] } }),
        serde_json::json!({ "name" : "show", "description" :
        "Show the current authored handler source for an operation. `method` is an operation name from `query` (kind `operation`). With `port`, `method` names one of that port's methods and the adapter method shows instead — `adapter` picks the implementing type when the file holds more than one. For a method with no authored source yet, it returns the generated signature, so you can read the request and response types before authoring. Example: `{ \"method\": \"verify\" }`.",
        "input_schema" : { "type" : "object", "properties" : { "method" : { "type" :
        "string" }, "port" : { "type" : "string" }, "adapter" : { "type" : "string" } },
        "required" : ["method"] } }), serde_json::json!({ "name" : "check", "description"
        :
        "Compile-check the workspace and report the outcome. `implement` runs it after each write on its own. Call it directly after a `patch` that writes, or to prove the tree compiles before a rebuild.",
        "input_schema" : { "type" : "object", "properties" : {} } }), serde_json::json!({
        "name" : "test", "description" :
        "Run the workspace tests and report the outcome. Slower than check; use it when behavior matters.",
        "input_schema" : { "type" : "object", "properties" : {} } })
    ]
}
pub(crate) fn parse_query_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<QueryRequest> {
    Ok(QueryRequest {
        find: serde_json::from_value(
                input.get("find").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `find` field is invalid: {error}"))?,
        node: serde_json::from_value(
                input.get("node").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `node` field is invalid: {error}"))?,
        kind: serde_json::from_value(
                input.get("kind").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `kind` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_patch_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<PatchRequest> {
    Ok(PatchRequest {
        edit: match input.get("edit") {
            None => Default::default(),
            Some(value) => {
                serde_json::from_value(value.clone())
                    .map_err(|error| {
                        anyhow::anyhow!("the `edit` field is invalid: {error}")
                    })?
            }
        },
        write: input
            .get("write")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or_default(),
    })
}
pub(crate) fn parse_implement_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ImplementRequest> {
    Ok(ImplementRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        body: input
            .get("body")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `body`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}
pub(crate) fn parse_show_request_input(
    input: &serde_json::Value,
) -> anyhow::Result<ShowRequest> {
    Ok(ShowRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}

/// Dispatch one tool call to the service: parse the request from the
/// call's JSON input, run the operation, and render the result — text
/// for a string, otherwise JSON. The catalog and this dispatch render
/// from the same contract, so every catalog entry has an arm here.
pub async fn dispatch_tool(
    service: &impl TheseusService,
    name: &str,
    input: &serde_json::Value,
) -> anyhow::Result<String> {
    match name {
        "model" => Ok(service.model().await?),
        "verify" => Ok(serde_json::to_string(&service.verify().await?)?),
        "query" => {
            Ok(
                serde_json::to_string(
                    &service.query(parse_query_request_input(input)?).await?,
                )?,
            )
        }
        "patch" => {
            Ok(
                serde_json::to_string(
                    &service.patch(parse_patch_request_input(input)?).await?,
                )?,
            )
        }
        "coverage" => Ok(serde_json::to_string(&service.coverage().await?)?),
        "implement" => {
            Ok(service.implement(parse_implement_request_input(input)?).await?)
        }
        "show" => Ok(service.show(parse_show_request_input(input)?).await?),
        "check" => Ok(service.check().await?),
        "test" => Ok(service.test().await?),
        other => {
            anyhow::bail!(
                "unknown tool `{other}`; tools are model, verify, query, patch, coverage, implement, show, check, test"
            )
        }
    }
}
