// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: command surface, request types, invocation, service contract, default presentation, outbound ports, composition root.

use clap::{Arg, ArgAction, ArgMatches, Command};
/// Build the command surface from the model.
pub fn command() -> Command {
    Command::new("calculator")
        .about("The Calculator service.")
        .arg_required_else_help(true)
        .subcommand(
            Command::new("add")
                .about("Add the operands.")
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
        .subcommand(
            Command::new("subtract")
                .about("Subtract the operands.")
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
        .subcommand(
            Command::new("multiply")
                .about("Multiply the operands.")
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
        .subcommand(
            Command::new("divide")
                .about("Divide the operands.")
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
}
fn parse_operands(matches: &ArgMatches) -> theseus_calculator::Operands {
    theseus_calculator::Operands {
        a: matches.get_one::<f64>("a").cloned().unwrap_or_default(),
        b: matches.get_one::<f64>("b").cloned().unwrap_or_default(),
    }
}
pub enum Invocation {
    Add(theseus_calculator::Operands),
    Subtract(theseus_calculator::Operands),
    Multiply(theseus_calculator::Operands),
    Divide(theseus_calculator::Operands),
}
impl Invocation {
    /// Parse the invocation from the matched command line.
    pub fn from_matches(matches: &ArgMatches) -> Self {
        match matches.subcommand() {
            Some(("add", sub)) => Invocation::Add(parse_operands(sub)),
            Some(("subtract", sub)) => Invocation::Subtract(parse_operands(sub)),
            Some(("multiply", sub)) => Invocation::Multiply(parse_operands(sub)),
            Some(("divide", sub)) => Invocation::Divide(parse_operands(sub)),
            _ => unreachable!("arg_required_else_help guarantees a subcommand"),
        }
    }
}
/// Render an operation's result with the default presentation.
pub fn present(
    service: &impl theseus_calculator::CalculatorService,
    invocation: Invocation,
) -> anyhow::Result<()> {
    match invocation {
        Invocation::Add(request) => println!("{}", service.add(request) ?),
        Invocation::Subtract(request) => println!("{}", service.subtract(request) ?),
        Invocation::Multiply(request) => println!("{}", service.multiply(request) ?),
        Invocation::Divide(request) => println!("{}", service.divide(request) ?),
    }
    Ok(())
}
