//! Code generation: planks rendered from a model.
//!
//! This is the Ship-of-Theseus move and the seed of the generation engine. From
//! the model it renders the CLI's inbound adapter (the command surface), the
//! typed request structs, the inbound service trait each operation must satisfy,
//! the outbound port traits a service depends on, and the composition root that
//! carries the wired ports. The hand-written adapters and the service impl are the
//! authored leaves, and regeneration writes only the generated file, so the leaves
//! stay intact. An adopter pairs the rendered contents with an output path.
//! [`verify`](crate::verify) drift-gates the result.
//!
//! The render builds a token stream and formats it with `prettyplease`, so the
//! output is canonical and stable across regenerations. The generated file carries
//! an `@generated` marker, and `rustfmt` is configured to leave such files alone,
//! so the drift gate compares like for like.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use serde::Serialize;

use crate::model::{Field, Model, Operation, Port, Service, TypeDef, TypeShape};

/// A file rendered from the model, addressed relative to the workspace root. An
/// adopter sets the path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

/// Render the generated scaffolding as formatted Rust source.
pub fn render_cli_module(model: &Model) -> String {
    let ports = outbound_ports(model);
    let port_traits: Vec<TokenStream> = ports
        .iter()
        .map(|port| render_port_trait(port, model))
        .collect();
    let composition_root = if ports.is_empty() {
        quote! {}
    } else {
        render_composition_root(&ports)
    };

    let command = render_command(model);
    let (requests, invocation, service_trait, present) = match model.services.first() {
        Some(service) => (
            render_request_structs(service, model),
            render_invocation(service, model),
            render_service_trait(service, model),
            render_present(service, model),
        ),
        None => (quote! {}, quote! {}, quote! {}, quote! {}),
    };

    let tokens = quote! {
        use clap::{Arg, ArgAction, ArgMatches, Command};

        #command
        #(#port_traits)*
        #composition_root
        #requests
        #invocation
        #service_trait
        #present
    };

    let file = syn::parse2(tokens).expect("generated code is valid Rust syntax");
    let body = prettyplease::unparse(&file);

    let mut out = String::from("// @generated by `theseus generate` — do not edit by hand.\n");
    out.push_str(
        "//! Theseus's generated scaffolding: command surface, request types, invocation, service contract, default presentation, outbound ports, composition root.\n\n",
    );
    out.push_str(&body);
    out
}

/// A `#[doc = " ..."]` attribute. `prettyplease` renders it as a `///` line.
fn doc(text: &str) -> TokenStream {
    let line = format!(" {text}");
    quote! { #[doc = #line] }
}

/// Every outbound port across all services.
fn outbound_ports(model: &Model) -> Vec<&Port> {
    model
        .services
        .iter()
        .flat_map(|service| service.outbound.iter())
        .collect()
}

/// Render the command surface: one subcommand per operation.
fn render_command(model: &Model) -> TokenStream {
    let bin = model.name.to_lowercase();
    let subcommands: Vec<TokenStream> = model
        .operations()
        .into_iter()
        .map(|op| render_subcommand(op, model))
        .collect();
    let doc = doc("Build the command surface from the model.");
    quote! {
        #doc
        pub fn command() -> Command {
            Command::new(#bin)
                .about("A self-modeling CLI seed.")
                .arg_required_else_help(true)
                #(#subcommands)*
        }
    }
}

/// Render one operation as a subcommand, its request fields as arguments.
fn render_subcommand(op: &Operation, model: &Model) -> TokenStream {
    let name = &op.name;
    let summary = &op.summary;
    let args: Vec<TokenStream> = request_fields(op, model).iter().map(render_arg).collect();
    quote! {
        .subcommand(Command::new(#name).about(#summary) #(#args)*)
    }
}

/// The fields of an operation's request type. They become its CLI arguments. An
/// `Empty` or undefined request contributes none.
fn request_fields<'a>(op: &Operation, model: &'a Model) -> &'a [Field] {
    match model.type_def(&op.request).map(|def| &def.shape) {
        Some(TypeShape::Struct(fields)) => fields,
        _ => &[],
    }
}

/// Render one request field as a command-line argument. The field type decides
/// the shape: `bool` is a flag, `Vec<T>` a repeatable value, `Option<T>` an
/// optional value, anything else a required value. A non-`String` value type is
/// parsed and validated as that type.
fn render_arg(field: &Field) -> TokenStream {
    let flag = field.name.replace('_', "-");
    let help = &field.doc;
    if field.ty == "bool" {
        quote! { .arg(Arg::new(#flag).long(#flag).action(ArgAction::SetTrue).help(#help)) }
    } else if field.ty.starts_with("Vec<") {
        quote! { .arg(Arg::new(#flag).long(#flag).action(ArgAction::Append).help(#help)) }
    } else if let Some(inner) = optional_inner(&field.ty) {
        let parser = value_parser(inner);
        quote! { .arg(Arg::new(#flag).long(#flag).action(ArgAction::Set) #parser .help(#help)) }
    } else {
        let parser = value_parser(&field.ty);
        quote! { .arg(Arg::new(#flag).long(#flag).action(ArgAction::Set).required(true) #parser .help(#help)) }
    }
}

/// The `.value_parser(...)` fragment for a typed argument. A `String` value needs
/// none. Any other value type is parsed and validated as that type.
fn value_parser(ty: &str) -> TokenStream {
    if ty == "String" {
        quote! {}
    } else {
        let ty = syn_type(ty);
        quote! { .value_parser(clap::value_parser!(#ty)) }
    }
}

/// The element type of an `Option<…>` label, when the label is one.
fn optional_inner(ty: &str) -> Option<&str> {
    ty.strip_prefix("Option<")?.strip_suffix('>')
}

/// Render one outbound port as a trait. The hand-written adapter implements it.
fn render_port_trait(port: &Port, model: &Model) -> TokenStream {
    let trait_name = format_ident!("{}", pascal_case(&port.name));
    let trait_doc = doc(&port.summary);
    let methods: Vec<TokenStream> = port
        .methods
        .iter()
        .map(|method| {
            let method_doc = doc(&method.summary);
            let method_name = format_ident!("{}", method.name);
            let param = request_param(&method.request, model);
            let response = response_type(&method.response, model);
            quote! {
                #method_doc
                fn #method_name(&self #param) -> anyhow::Result<#response>;
            }
        })
        .collect();
    quote! {
        #trait_doc
        pub trait #trait_name {
            #(#methods)*
        }
    }
}

/// Render the composition root: the model plus one field per wired port.
fn render_composition_root(ports: &[&Port]) -> TokenStream {
    let fields: Vec<TokenStream> = ports
        .iter()
        .map(|port| {
            let field = format_ident!("{}", snake_case(&port.name));
            let trait_name = format_ident!("{}", pascal_case(&port.name));
            quote! { pub #field: &'a dyn #trait_name, }
        })
        .collect();
    let doc = doc("Composition root: the model plus the wired outbound ports.");
    quote! {
        #doc
        pub struct Ctx<'a> {
            pub model: &'a theseus_modeling::Model,
            #(#fields)*
        }
    }
}

/// Render each distinct request struct used by the service's operations.
fn render_request_structs(service: &Service, model: &Model) -> TokenStream {
    let mut seen: Vec<&str> = Vec::new();
    let structs: Vec<TokenStream> = service
        .operations
        .iter()
        .filter_map(|op| request_type(op, model))
        .filter(|def| {
            let fresh = !seen.contains(&def.name.as_str());
            if fresh {
                seen.push(&def.name);
            }
            fresh
        })
        .map(render_request_struct)
        .collect();
    quote! { #(#structs)* }
}

/// The request type an operation takes, if its request names a defined struct.
/// `Empty` and undefined requests yield `None`, so the operation takes no request.
fn request_type<'a>(op: &Operation, model: &'a Model) -> Option<&'a TypeDef> {
    if op.request == "Empty" {
        return None;
    }
    model
        .type_def(&op.request)
        .filter(|def| matches!(def.shape, TypeShape::Struct(_)))
}

/// Render a request struct plus the parser that builds it from command-line
/// arguments. This is the inbound adapter's wire-to-domain conversion, kept out of
/// the service so the service stays transport-neutral.
fn render_request_struct(def: &TypeDef) -> TokenStream {
    let TypeShape::Struct(fields) = &def.shape else {
        return quote! {};
    };
    let name = format_ident!("{}", def.name);
    let struct_doc = doc(&format!(
        "The `{}` request, parsed from command-line arguments.",
        def.name
    ));

    let field_defs: Vec<TokenStream> = fields
        .iter()
        .map(|field| {
            let field_doc = doc(&field.doc);
            let field_name = format_ident!("{}", field.name);
            let field_type = syn_type(&field.ty);
            quote! {
                #field_doc
                pub #field_name: #field_type,
            }
        })
        .collect();

    // The `arg` closure reads a single optional string; emit it only when a field
    // reads one (flags, repeatable values, and typed values read the matches with
    // their own type).
    let arg_closure = if fields
        .iter()
        .any(|field| field.ty == "String" || field.ty == "Option<String>")
    {
        quote! { let arg = |name: &str| matches.get_one::<String>(name).cloned(); }
    } else {
        quote! {}
    };
    let field_inits: Vec<TokenStream> = fields
        .iter()
        .map(|field| {
            let field_name = format_ident!("{}", field.name);
            let parse = field_parse(field);
            quote! { #field_name: #parse, }
        })
        .collect();

    quote! {
        #struct_doc
        #[derive(Debug, Clone)]
        pub struct #name {
            #(#field_defs)*
        }

        impl #name {
            /// Build the request from parsed command-line arguments.
            fn from_matches(matches: &ArgMatches) -> Self {
                #arg_closure
                #name {
                    #(#field_inits)*
                }
            }
        }
    }
}

/// The expression that reads one request field from the parsed arguments: a flag
/// for `bool`, the collected values for `Vec<T>`, an optional value for
/// `Option<T>`, otherwise a required value. A non-`String` value is read as its
/// parsed type.
fn field_parse(field: &Field) -> TokenStream {
    let flag = field.name.replace('_', "-");
    if field.ty == "bool" {
        quote! { matches.get_flag(#flag) }
    } else if field.ty.starts_with("Vec<") {
        quote! { matches.get_many::<String>(#flag).map(|values| values.cloned().collect()).unwrap_or_default() }
    } else if let Some(inner) = optional_inner(&field.ty) {
        if inner == "String" {
            quote! { arg(#flag) }
        } else {
            let inner = syn_type(inner);
            quote! { matches.get_one::<#inner>(#flag).cloned() }
        }
    } else if field.ty == "String" {
        quote! { arg(#flag).unwrap_or_default() }
    } else {
        let ty = syn_type(&field.ty);
        quote! { matches.get_one::<#ty>(#flag).cloned().unwrap_or_default() }
    }
}

/// Render the inbound service trait: one method per operation, each defaulting to
/// an `unimplemented` error. The authored impl overrides the operations it
/// implements. An operation left on its default still compiles, and `verify`'s
/// coverage check reports it.
fn render_service_trait(service: &Service, model: &Model) -> TokenStream {
    let trait_name = format_ident!("{}Service", pascal_case(&service.name));
    let doc_a = doc("The inbound service contract: one method per operation, each defaulting");
    let doc_b = doc("to `unimplemented`. The authored impl overrides what it implements.");
    let methods: Vec<TokenStream> = service
        .operations
        .iter()
        .map(|op| {
            let method_doc = doc(&op.summary);
            let method_name = format_ident!("{}", op.name);
            let param = match request_type(op, model) {
                Some(def) => {
                    let request = format_ident!("{}", def.name);
                    quote! { , _request: #request }
                }
                None => quote! {},
            };
            let response = response_type(&op.response, model);
            let unimplemented = format!("unimplemented operation: {}", op.name);
            quote! {
                #method_doc
                fn #method_name(&self #param) -> anyhow::Result<#response> {
                    anyhow::bail!(#unimplemented)
                }
            }
        })
        .collect();
    quote! {
        #doc_a
        #doc_b
        pub trait #trait_name {
            #(#methods)*
        }
    }
}

/// Render the parsed-invocation enum: one variant per operation, carrying its
/// request. The authored presenter matches on it exhaustively, so a new operation
/// forces a presentation decision rather than a runtime surprise.
fn render_invocation(service: &Service, model: &Model) -> TokenStream {
    let variants: Vec<TokenStream> = service
        .operations
        .iter()
        .map(|op| {
            let variant = format_ident!("{}", pascal_case(&op.name));
            let variant_doc = doc(&op.summary);
            match request_type(op, model) {
                Some(def) => {
                    let request = format_ident!("{}", def.name);
                    quote! { #variant_doc #variant(#request), }
                }
                None => quote! { #variant_doc #variant, },
            }
        })
        .collect();
    let arms: Vec<TokenStream> = service
        .operations
        .iter()
        .map(|op| {
            let name = &op.name;
            let variant = format_ident!("{}", pascal_case(&op.name));
            match request_type(op, model) {
                Some(def) => {
                    let request = format_ident!("{}", def.name);
                    quote! { Some((#name, sub)) => Invocation::#variant(#request::from_matches(sub)), }
                }
                None => quote! { Some((#name, _)) => Invocation::#variant, },
            }
        })
        .collect();
    let enum_doc = doc("A parsed invocation: one variant per operation, carrying its request.");
    let fn_doc = doc("Parse the invocation from the matched command line.");
    quote! {
        #enum_doc
        pub enum Invocation {
            #(#variants)*
        }

        impl Invocation {
            #fn_doc
            pub fn from_matches(matches: &ArgMatches) -> Self {
                match matches.subcommand() {
                    #(#arms)*
                    _ => unreachable!("arg_required_else_help guarantees a subcommand"),
                }
            }
        }
    }
}

/// Render the default presentation: dispatch each operation and render its result
/// as text for a `String`, otherwise pretty JSON. The authored presenter overrides
/// the operations that need bespoke output and delegates the rest here, so the
/// response side of the surface is generated like the request side.
fn render_present(service: &Service, model: &Model) -> TokenStream {
    let trait_name = format_ident!("{}Service", pascal_case(&service.name));
    let arms: Vec<TokenStream> = service
        .operations
        .iter()
        .map(|op| {
            let variant = format_ident!("{}", pascal_case(&op.name));
            let method = format_ident!("{}", op.name);
            let (pattern, call) = match request_type(op, model) {
                Some(_) => (
                    quote! { Invocation::#variant(request) },
                    quote! { service.#method(request)? },
                ),
                None => (
                    quote! { Invocation::#variant },
                    quote! { service.#method()? },
                ),
            };
            let render = if rust_type(&op.response, model) == "String" {
                quote! { println!("{}", #call) }
            } else {
                quote! { println!("{}", serde_json::to_string_pretty(&#call)?) }
            };
            quote! { #pattern => #render, }
        })
        .collect();
    let doc_a = doc("Render an operation with the default presentation: text for a string,");
    let doc_b = doc("otherwise pretty JSON. The authored presenter delegates here.");
    quote! {
        #doc_a
        #doc_b
        pub fn present(service: &impl #trait_name, invocation: Invocation) -> anyhow::Result<()> {
            match invocation {
                #(#arms)*
            }
            Ok(())
        }
    }
}

/// The response type a method returns, as a parsed Rust type.
fn response_type(label: &str, model: &Model) -> TokenStream {
    let ty = syn_type(&rust_type(label, model));
    quote! { #ty }
}

/// Render an operation's handler signature, for splicing an authored body. The
/// request is named through `request_path` and the response resolves to an
/// absolute type, so the spliced method needs no imports.
pub(crate) fn handler_signature(op: &Operation, model: &Model, request_path: &str) -> String {
    let param = match request_type(op, model) {
        Some(def) => format!(", request: {request_path}{}", def.name),
        None => String::new(),
    };
    let response = rust_type(&op.response, model);
    format!(
        "fn {}(&self{param}) -> anyhow::Result<{response}>",
        op.name
    )
}

/// The `, request: &T` fragment for a method, or empty for an `Empty` request.
/// `String` requests borrow as `&str`, the idiomatic borrowed form.
fn request_param(label: &str, model: &Model) -> TokenStream {
    if label == "Empty" {
        return quote! {};
    }
    let ty = rust_type(label, model);
    if ty == "String" {
        quote! { , request: &str }
    } else {
        let ty = syn_type(&ty);
        quote! { , request: &#ty }
    }
}

/// The Rust type a model type label maps to, used for method responses.
fn rust_type(label: &str, model: &Model) -> String {
    match label {
        "Empty" => "()".to_string(),
        "String" => "String".to_string(),
        other => match model.types.iter().find(|t| t.name == other) {
            Some(def) => match &def.shape {
                TypeShape::Newtype(inner) => inner.clone(),
                TypeShape::Foreign(path) => path.clone(),
                _ => format!("theseus_modeling::{other}"),
            },
            None => other.to_string(),
        },
    }
}

/// Parse a rendered type string into a token type, e.g. `()` or `Option<String>`.
fn syn_type(text: &str) -> syn::Type {
    syn::parse_str(text).expect("rendered type is valid Rust")
}

pub(crate) fn pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake_case(name: &str) -> String {
    name.replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Model, Service, Transport};

    #[test]
    fn case_helpers() {
        assert_eq!(pascal_case("source-store"), "SourceStore");
        assert_eq!(snake_case("source-store"), "source_store");
    }

    #[test]
    fn a_typed_request_field_parses_as_its_type() {
        let model = Model::new("Calc")
            .struct_type("Operands", &[("a", "f64", "Left operand.")])
            .service(Service::new("Calc", Transport::Cli).operation(
                "add",
                "Add.",
                "Operands",
                "Empty",
            ));
        let rendered = render_cli_module(&model);
        // The argument validates as the field type, and the field reads it back.
        assert!(rendered.contains("value_parser"));
        assert!(rendered.contains("get_one::<f64>"));
        assert!(rendered.contains("pub a: f64"));
    }
}
