// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: command surface, request types, invocation, service contract, dispatch, outbound ports, composition root.

/// The `Operands` request.
#[derive(Debug, Clone)]
pub struct Operands {
    /// Left operand.
    pub a: f64,
    /// Right operand.
    pub b: f64,
}
/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
pub trait CalculatorService {
    /// Add the operands.
    fn add(&self, _request: Operands) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: add")
    }
    /// Subtract the operands.
    fn subtract(&self, _request: Operands) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: subtract")
    }
    /// Multiply the operands.
    fn multiply(&self, _request: Operands) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: multiply")
    }
    /// Divide the operands.
    fn divide(&self, _request: Operands) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: divide")
    }
}
