// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract.

/// The `Operands` request.
#[derive(Debug, Clone)]
pub struct Operands {
    /// Left operand.
    pub a: f64,
    /// Right operand.
    pub b: f64,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}

/// A write refused by a permission gate. A transport adapter downcasts it
/// to map the refusal in its own vocabulary.
#[derive(Debug)]
pub struct Refused;

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "writes are not permitted; grant write permission to apply this edit")
    }
}

impl std::error::Error for Refused {}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
#[async_trait::async_trait]
pub trait CalculatorService: Send + Sync {
    /// Add the operands.
    async fn add(&self, _request: Operands) -> anyhow::Result<String> {
        Err(Unimplemented("add").into())
    }

    /// Subtract the operands.
    async fn subtract(&self, _request: Operands) -> anyhow::Result<String> {
        Err(Unimplemented("subtract").into())
    }

    /// Multiply the operands.
    async fn multiply(&self, _request: Operands) -> anyhow::Result<String> {
        Err(Unimplemented("multiply").into())
    }

    /// Divide the operands.
    async fn divide(&self, _request: Operands) -> anyhow::Result<String> {
        Err(Unimplemented("divide").into())
    }
}
