// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the gRPC client over the service contract.

/// The wire types and client stub the build compiles from the proto.
pub mod proto {
    tonic::include_proto!("theseus");
}

/// The service contract carried over gRPC: each call converts its request
/// to the wire's message, and a status maps back onto the contract's error
/// classes. A composition root wires it where an in-process adapter would
/// stand.
pub struct GrpcTheseusClient {
    stub: proto::theseus_client::TheseusClient<tonic::transport::Channel>,
}

impl GrpcTheseusClient {
    /// Connect to `endpoint`, e.g. `http://127.0.0.1:4873`.
    pub async fn connect(endpoint: String) -> anyhow::Result<Self> {
        Ok(Self {
            stub: proto::theseus_client::TheseusClient::connect(endpoint).await?,
        })
    }
}

#[async_trait::async_trait]
impl theseus::TheseusService for GrpcTheseusClient {
    async fn model(&self) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .model(proto::Empty {})
            .await
            .map_err(|status| failed("model", status))?;
        Ok(reply.into_inner().value)
    }

    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        let reply = self
            .stub
            .clone()
            .verify(proto::Empty {})
            .await
            .map_err(|status| failed("verify", status))?;
        parsed("verify", &reply.into_inner().json)
    }

    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let reply = self
            .stub
            .clone()
            .generate(proto::Empty {})
            .await
            .map_err(|status| failed("generate", status))?;
        parsed("generate", &reply.into_inner().json)
    }

    async fn query(
        &self,
        request: theseus::QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        let reply = self
            .stub
            .clone()
            .query(proto::QueryRequest {
                find: request.find,
                node: request.node,
                kind: request.kind,
            })
            .await
            .map_err(|status| failed("query", status))?;
        parsed("query", &reply.into_inner().json)
    }

    async fn patch(
        &self,
        request: theseus::PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        let reply = self
            .stub
            .clone()
            .patch(proto::PatchRequest {
                edit: request.edit.into_iter().map(edit_to_proto).collect(),
                write: request.write,
            })
            .await
            .map_err(|status| failed("patch", status))?;
        parsed("patch", &reply.into_inner().json)
    }

    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        let reply = self
            .stub
            .clone()
            .coverage(proto::Empty {})
            .await
            .map_err(|status| failed("coverage", status))?;
        parsed("coverage", &reply.into_inner().json)
    }

    async fn implement(
        &self,
        request: theseus::ImplementRequest,
    ) -> anyhow::Result<theseus::ImplementResult> {
        let reply = self
            .stub
            .clone()
            .implement(proto::ImplementRequest {
                method: Some(request.method),
                body: Some(request.body),
                port: request.port,
                adapter: request.adapter,
            })
            .await
            .map_err(|status| failed("implement", status))?;
        parsed("implement", &reply.into_inner().json)
    }

    async fn edit_rust_item(
        &self,
        request: theseus::RustItemRequest,
    ) -> anyhow::Result<theseus::RustItemResult> {
        let reply = self
            .stub
            .clone()
            .edit_rust_item(proto::RustItemRequest {
                path: Some(request.path),
                revision: Some(request.revision),
                item: Some(request.item),
                replace: request.replace,
            })
            .await
            .map_err(|status| failed("edit_rust_item", status))?;
        parsed("edit_rust_item", &reply.into_inner().json)
    }

    async fn show(&self, request: theseus::ShowRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .show(proto::ShowRequest {
                method: Some(request.method),
                port: request.port,
                adapter: request.adapter,
            })
            .await
            .map_err(|status| failed("show", status))?;
        Ok(reply.into_inner().value)
    }

    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        let reply = self
            .stub
            .clone()
            .check(proto::Empty {})
            .await
            .map_err(|status| failed("check", status))?;
        parsed("check", &reply.into_inner().json)
    }

    async fn calc(&self, request: theseus::CalcRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .calc(proto::CalcRequest {
                op: Some(request.op),
                a: Some(request.a),
                b: Some(request.b),
            })
            .await
            .map_err(|status| failed("calc", status))?;
        Ok(reply.into_inner().value)
    }

    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let reply = self
            .stub
            .clone()
            .scaffold(proto::Empty {})
            .await
            .map_err(|status| failed("scaffold", status))?;
        parsed("scaffold", &reply.into_inner().json)
    }

    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        let reply = self
            .stub
            .clone()
            .test(proto::Empty {})
            .await
            .map_err(|status| failed("test", status))?;
        parsed("test", &reply.into_inner().json)
    }

    async fn snapshot(
        &self,
        request: theseus::SnapshotRequest,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .snapshot(proto::SnapshotRequest {
                label: Some(request.label),
            })
            .await
            .map_err(|status| failed("snapshot", status))?;
        Ok(reply.into_inner().value)
    }

    async fn rollback(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .rollback(proto::SnapshotRef {
                reference: Some(request.reference),
            })
            .await
            .map_err(|status| failed("rollback", status))?;
        Ok(reply.into_inner().value)
    }

    async fn release(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .release(proto::SnapshotRef {
                reference: Some(request.reference),
            })
            .await
            .map_err(|status| failed("release", status))?;
        Ok(reply.into_inner().value)
    }

    async fn prune(
        &self,
        request: theseus::SnapshotRetention,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .prune(proto::SnapshotRetention {
                keep: Some(request.keep),
            })
            .await
            .map_err(|status| failed("prune", status))?;
        Ok(reply.into_inner().value)
    }

    async fn diff(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .diff(proto::SnapshotRef {
                reference: Some(request.reference),
            })
            .await
            .map_err(|status| failed("diff", status))?;
        Ok(reply.into_inner().value)
    }

    async fn restart(&self) -> anyhow::Result<()> {
        let reply = self
            .stub
            .clone()
            .restart(proto::Empty {})
            .await
            .map_err(|status| failed("restart", status))?;
        reply.into_inner();
        Ok(())
    }

    async fn read(
        &self,
        request: theseus::ReadRequest,
    ) -> anyhow::Result<theseus::SourceDocument> {
        let reply = self
            .stub
            .clone()
            .read(proto::ReadRequest {
                path: Some(request.path),
            })
            .await
            .map_err(|status| failed("read", status))?;
        parsed("read", &reply.into_inner().json)
    }

    async fn search(&self, request: theseus::SearchRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .search(proto::SearchRequest {
                pattern: Some(request.pattern),
                path: request.path,
            })
            .await
            .map_err(|status| failed("search", status))?;
        Ok(reply.into_inner().value)
    }

    async fn list(&self, request: theseus::ListRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .list(proto::ListRequest {
                path: request.path,
            })
            .await
            .map_err(|status| failed("list", status))?;
        Ok(reply.into_inner().value)
    }

    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        let reply = self
            .stub
            .clone()
            .lint(proto::Empty {})
            .await
            .map_err(|status| failed("lint", status))?;
        parsed("lint", &reply.into_inner().json)
    }

    async fn drive(&self, request: theseus::DriveRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .drive(proto::DriveRequest {
                operation: Some(request.operation),
                input: request.input,
            })
            .await
            .map_err(|status| failed("drive", status))?;
        Ok(reply.into_inner().value)
    }

    async fn skills(&self, request: theseus::SkillsRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .skills(proto::SkillsRequest {
                topic: request.topic,
            })
            .await
            .map_err(|status| failed("skills", status))?;
        Ok(reply.into_inner().value)
    }

    async fn explain(&self, request: theseus::ExplainRequest) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .explain(proto::ExplainRequest {
                code: request.code,
            })
            .await
            .map_err(|status| failed("explain", status))?;
        Ok(reply.into_inner().value)
    }
}

/// Convert the contract's Edit to the wire's, verb by verb.
fn edit_to_proto(value: theseus_modeling::Edit) -> proto::Edit {
    match value {
        theseus_modeling::Edit::Add { parent, kind, name, attrs } => {
            proto::Edit {
                verb: Some(
                    proto::edit::Verb::Add(proto::edit::Add {
                        parent: Some(parent),
                        kind: Some(kind),
                        name: Some(name),
                        attrs: attrs.into_iter().collect(),
                    }),
                ),
            }
        }
        theseus_modeling::Edit::Remove { target } => {
            proto::Edit {
                verb: Some(
                    proto::edit::Verb::Remove(proto::edit::Remove {
                        target: Some(target),
                    }),
                ),
            }
        }
        theseus_modeling::Edit::Rename { target, to } => {
            proto::Edit {
                verb: Some(
                    proto::edit::Verb::Rename(proto::edit::Rename {
                        target: Some(target),
                        to: Some(to),
                    }),
                ),
            }
        }
        theseus_modeling::Edit::Set { target, attrs } => {
            proto::Edit {
                verb: Some(
                    proto::edit::Verb::Set(proto::edit::Set {
                        target: Some(target),
                        attrs: attrs.into_iter().collect(),
                    }),
                ),
            }
        }
    }
}

/// Map a status back onto the contract: UNIMPLEMENTED is the typed
/// unimplemented default, PERMISSION_DENIED the typed refusal, anything
/// else the status itself.
fn failed(operation: &'static str, status: tonic::Status) -> anyhow::Error {
    match status.code() {
        tonic::Code::Unimplemented => theseus::Unimplemented(operation).into(),
        tonic::Code::PermissionDenied => theseus::Refused.into(),
        _ => anyhow::anyhow!("`{operation}` failed: {status}"),
    }
}

fn parsed<T: serde::de::DeserializeOwned>(
    operation: &'static str,
    body: &str,
) -> anyhow::Result<T> {
    serde_json::from_str(body)
        .map_err(|error| anyhow::anyhow!("`{operation}` reply did not parse: {error}"))
}
