// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract, the outbound port traits and composition roots.

/// Persists the journal's entries.
#[async_trait::async_trait]
pub trait Store: Send + Sync {
    /// Append one entry.
    async fn append(&self, _request: &str) -> anyhow::Result<()> {
        Err(Unimplemented("store.append").into())
    }

    /// Read every entry.
    async fn read_all(&self) -> anyhow::Result<String> {
        Err(Unimplemented("store.read_all").into())
    }
}

/// A borrowed adapter serves the port its target serves, so a wrapper
/// generic over the port holds a borrow as readily as an owned adapter.
#[async_trait::async_trait]
impl<T: Store + ?Sized> Store for &T {
    async fn append(&self, request: &str) -> anyhow::Result<()> {
        (**self).append(request).await
    }

    async fn read_all(&self) -> anyhow::Result<String> {
        (**self).read_all().await
    }
}

/// Composition root: the model plus the wired outbound ports.
pub struct Ctx<'a> {
    pub model: &'a theseus_modeling::Model,
    pub store: &'a dyn Store,
}

/// The `AddRequest` request.
#[derive(Debug, Clone)]
pub struct AddRequest {
    /// The entry to record.
    pub text: String,
}

/// The `SearchRequest` request.
#[derive(Debug, Clone)]
pub struct SearchRequest {
    /// The text to look for.
    pub term: String,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}

/// A write refused by a permission gate. A transport adapter downcasts it
/// to map the refusal in its own vocabulary.
#[derive(Debug)]
pub struct Refused;

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "writes are not permitted; grant write permission to apply this edit")
    }
}

impl std::error::Error for Refused {}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
#[async_trait::async_trait]
pub trait JournalService: Send + Sync {
    /// Record one journal entry.
    async fn add(&self, _request: AddRequest) -> anyhow::Result<String> {
        Err(Unimplemented("add").into())
    }

    /// Print every journal entry.
    async fn list(&self) -> anyhow::Result<String> {
        Err(Unimplemented("list").into())
    }

    /// Print the entries containing a term.
    async fn search(&self, _request: SearchRequest) -> anyhow::Result<String> {
        Err(Unimplemented("search").into())
    }
}

/// An owned composition root: the service over one owned adapter per port,
/// driven through a fresh borrowed `Ctx` per call. A long-lived inbound
/// holds it where a borrowed root cannot live.
pub struct Standalone<StoreAdapter: Store> {
    pub model: theseus_modeling::Model,
    pub store: StoreAdapter,
}

impl<StoreAdapter: Store> Standalone<StoreAdapter> {
    /// The borrowed composition root one call runs over.
    fn ctx(&self) -> Ctx<'_> {
        Ctx {
            model: &self.model,
            store: &self.store,
        }
    }
}

#[async_trait::async_trait]
impl<StoreAdapter: Store> JournalService for Standalone<StoreAdapter> {
    async fn add(&self, request: AddRequest) -> anyhow::Result<String> {
        self.ctx().add(request).await
    }

    async fn list(&self) -> anyhow::Result<String> {
        self.ctx().list().await
    }

    async fn search(&self, request: SearchRequest) -> anyhow::Result<String> {
        self.ctx().search(request).await
    }
}
