// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the request types and service contract.

/// The `SlugifyRequest` request.
#[derive(Debug, Clone)]
pub struct SlugifyRequest {
    /// The string to convert to a slug.
    pub input: String,
}

/// The `WordCountRequest` request.
#[derive(Debug, Clone)]
pub struct WordCountRequest {
    /// The string whose words to count.
    pub input: String,
}

/// The `TruncateRequest` request.
#[derive(Debug, Clone)]
pub struct TruncateRequest {
    /// The string to truncate.
    pub input: String,
    /// Maximum number of characters to keep before appending ellipsis.
    pub max_chars: u32,
}

/// The `CapitalizeRequest` request.
#[derive(Debug, Clone)]
pub struct CapitalizeRequest {
    /// The string to title-case.
    pub input: String,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}

/// A write refused by a permission gate. A transport adapter downcasts it
/// to map the refusal in its own vocabulary.
#[derive(Debug)]
pub struct Refused;

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "writes are not permitted; grant write permission to apply this edit")
    }
}

impl std::error::Error for Refused {}

/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
#[async_trait::async_trait]
pub trait TextUtilsService: Send + Sync {
    /// Convert a string to a URL-safe slug.
    async fn slugify(&self, _request: SlugifyRequest) -> anyhow::Result<String> {
        Err(Unimplemented("slugify").into())
    }

    /// Count the words in a string.
    async fn word_count(&self, _request: WordCountRequest) -> anyhow::Result<String> {
        Err(Unimplemented("word_count").into())
    }

    /// Truncate a string to at most N characters, appending an ellipsis when cut.
    async fn truncate(&self, _request: TruncateRequest) -> anyhow::Result<String> {
        Err(Unimplemented("truncate").into())
    }

    /// Capitalize the first letter of every word (title case).
    async fn capitalize(&self, _request: CapitalizeRequest) -> anyhow::Result<String> {
        Err(Unimplemented("capitalize").into())
    }
}
