// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the gRPC client over the service contract.

/// The wire types and client stub the build compiles from the proto.
pub mod proto {
    tonic::include_proto!("theseus.calculator");
}

/// The service contract carried over gRPC: each call converts its request
/// to the wire's message, and a status maps back onto the contract's error
/// classes. A composition root wires it where an in-process adapter would
/// stand.
pub struct GrpcCalculatorClient {
    stub: proto::calculator_client::CalculatorClient<tonic::transport::Channel>,
}

impl GrpcCalculatorClient {
    /// Connect to `endpoint`, e.g. `http://127.0.0.1:4873`.
    pub async fn connect(endpoint: String) -> anyhow::Result<Self> {
        Ok(Self {
            stub: proto::calculator_client::CalculatorClient::connect(endpoint).await?,
        })
    }
}

#[async_trait::async_trait]
impl theseus_calculator::CalculatorService for GrpcCalculatorClient {
    async fn add(
        &self,
        request: theseus_calculator::Operands,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .add(proto::Operands {
                a: request.a,
                b: request.b,
            })
            .await
            .map_err(|status| failed("add", status))?;
        Ok(reply.into_inner().value)
    }
    async fn subtract(
        &self,
        request: theseus_calculator::Operands,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .subtract(proto::Operands {
                a: request.a,
                b: request.b,
            })
            .await
            .map_err(|status| failed("subtract", status))?;
        Ok(reply.into_inner().value)
    }
    async fn multiply(
        &self,
        request: theseus_calculator::Operands,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .multiply(proto::Operands {
                a: request.a,
                b: request.b,
            })
            .await
            .map_err(|status| failed("multiply", status))?;
        Ok(reply.into_inner().value)
    }
    async fn divide(
        &self,
        request: theseus_calculator::Operands,
    ) -> anyhow::Result<String> {
        let reply = self
            .stub
            .clone()
            .divide(proto::Operands {
                a: request.a,
                b: request.b,
            })
            .await
            .map_err(|status| failed("divide", status))?;
        Ok(reply.into_inner().value)
    }
}

/// Map a status back onto the contract: UNIMPLEMENTED is the typed
/// unimplemented default, PERMISSION_DENIED the typed refusal, anything
/// else the status itself.
fn failed(operation: &'static str, status: tonic::Status) -> anyhow::Error {
    match status.code() {
        tonic::Code::Unimplemented => theseus_calculator::Unimplemented(operation).into(),
        tonic::Code::PermissionDenied => theseus_modeling::Refused.into(),
        _ => anyhow::anyhow!("`{operation}` failed: {status}"),
    }
}
