// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the HTTP client over the service contract.

/// The service contract carried over HTTP: each call posts its request as
/// a JSON body, and the reply's status maps back onto the contract's error
/// classes. A composition root wires it where an in-process adapter would
/// stand.
pub struct HttpTheseusClient {
    base_url: String,
    http: reqwest::Client,
}

impl HttpTheseusClient {
    /// A client against `base_url`, e.g. `http://127.0.0.1:4870`.
    pub fn new(base_url: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            http: reqwest::Client::new(),
        }
    }

    /// Post one operation call and read the reply.
    async fn post(
        &self,
        operation: &str,
        body: serde_json::Value,
    ) -> anyhow::Result<(u16, String)> {
        let response = self
            .http
            .post(format!("{}/{operation}", self.base_url))
            .json(&body)
            .send()
            .await?;
        let status = response.status().as_u16();
        let body = response.text().await?;
        Ok((status, body))
    }
}

#[async_trait::async_trait]
impl theseus::TheseusService for HttpTheseusClient {
    async fn model(&self) -> anyhow::Result<String> {
        let (status, body) = self.post("model", serde_json::json!({})).await?;
        checked("model", status, &body)?;
        Ok(body)
    }

    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        let (status, body) = self.post("verify", serde_json::json!({})).await?;
        checked("verify", status, &body)?;
        parsed("verify", &body)
    }

    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let (status, body) = self.post("generate", serde_json::json!({})).await?;
        checked("generate", status, &body)?;
        parsed("generate", &body)
    }

    async fn query(
        &self,
        request: theseus::QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        let (status, body) = self
            .post(
                "query",
                serde_json::json!(
                    { "find" : request.find, "node" : request.node, "kind" : request.kind
                    }
                ),
            )
            .await?;
        checked("query", status, &body)?;
        parsed("query", &body)
    }

    async fn patch(
        &self,
        request: theseus::PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        let (status, body) = self
            .post(
                "patch",
                serde_json::json!({ "edit" : request.edit, "write" : request.write }),
            )
            .await?;
        checked("patch", status, &body)?;
        parsed("patch", &body)
    }

    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        let (status, body) = self.post("coverage", serde_json::json!({})).await?;
        checked("coverage", status, &body)?;
        parsed("coverage", &body)
    }

    async fn implement(
        &self,
        request: theseus::ImplementRequest,
    ) -> anyhow::Result<theseus::ImplementResult> {
        let (status, body) = self
            .post(
                "implement",
                serde_json::json!(
                    { "method" : request.method, "body" : request.body, "port" : request
                    .port, "adapter" : request.adapter }
                ),
            )
            .await?;
        checked("implement", status, &body)?;
        parsed("implement", &body)
    }

    async fn edit_rust_item(
        &self,
        request: theseus::RustItemRequest,
    ) -> anyhow::Result<theseus::RustItemResult> {
        let (status, body) = self
            .post(
                "edit_rust_item",
                serde_json::json!(
                    { "path" : request.path, "revision" : request.revision, "item" :
                    request.item, "replace" : request.replace }
                ),
            )
            .await?;
        checked("edit_rust_item", status, &body)?;
        parsed("edit_rust_item", &body)
    }

    async fn show(&self, request: theseus::ShowRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "show",
                serde_json::json!(
                    { "method" : request.method, "port" : request.port, "adapter" :
                    request.adapter }
                ),
            )
            .await?;
        checked("show", status, &body)?;
        Ok(body)
    }

    async fn check(&self) -> anyhow::Result<theseus::CheckReport> {
        let (status, body) = self.post("check", serde_json::json!({})).await?;
        checked("check", status, &body)?;
        parsed("check", &body)
    }

    async fn calc(&self, request: theseus::CalcRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "calc",
                serde_json::json!(
                    { "op" : request.op, "a" : request.a, "b" : request.b }
                ),
            )
            .await?;
        checked("calc", status, &body)?;
        Ok(body)
    }

    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let (status, body) = self.post("scaffold", serde_json::json!({})).await?;
        checked("scaffold", status, &body)?;
        parsed("scaffold", &body)
    }

    async fn test(&self) -> anyhow::Result<theseus::CheckReport> {
        let (status, body) = self.post("test", serde_json::json!({})).await?;
        checked("test", status, &body)?;
        parsed("test", &body)
    }

    async fn snapshot(
        &self,
        request: theseus::SnapshotRequest,
    ) -> anyhow::Result<String> {
        let (status, body) = self
            .post("snapshot", serde_json::json!({ "label" : request.label }))
            .await?;
        checked("snapshot", status, &body)?;
        Ok(body)
    }

    async fn rollback(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let (status, body) = self
            .post("rollback", serde_json::json!({ "reference" : request.reference }))
            .await?;
        checked("rollback", status, &body)?;
        Ok(body)
    }

    async fn release(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let (status, body) = self
            .post("release", serde_json::json!({ "reference" : request.reference }))
            .await?;
        checked("release", status, &body)?;
        Ok(body)
    }

    async fn prune(
        &self,
        request: theseus::SnapshotRetention,
    ) -> anyhow::Result<String> {
        let (status, body) = self
            .post("prune", serde_json::json!({ "keep" : request.keep }))
            .await?;
        checked("prune", status, &body)?;
        Ok(body)
    }

    async fn diff(&self, request: theseus::SnapshotRef) -> anyhow::Result<String> {
        let (status, body) = self
            .post("diff", serde_json::json!({ "reference" : request.reference }))
            .await?;
        checked("diff", status, &body)?;
        Ok(body)
    }

    async fn restart(&self) -> anyhow::Result<()> {
        let (status, body) = self.post("restart", serde_json::json!({})).await?;
        checked("restart", status, &body)?;
        Ok(())
    }

    async fn read(
        &self,
        request: theseus::ReadRequest,
    ) -> anyhow::Result<theseus::SourceDocument> {
        let (status, body) = self
            .post("read", serde_json::json!({ "path" : request.path }))
            .await?;
        checked("read", status, &body)?;
        parsed("read", &body)
    }

    async fn search(&self, request: theseus::SearchRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "search",
                serde_json::json!({ "pattern" : request.pattern, "path" : request.path }),
            )
            .await?;
        checked("search", status, &body)?;
        Ok(body)
    }

    async fn list(&self, request: theseus::ListRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post("list", serde_json::json!({ "path" : request.path }))
            .await?;
        checked("list", status, &body)?;
        Ok(body)
    }

    async fn lint(&self) -> anyhow::Result<theseus::CheckReport> {
        let (status, body) = self.post("lint", serde_json::json!({})).await?;
        checked("lint", status, &body)?;
        parsed("lint", &body)
    }

    async fn drive(&self, request: theseus::DriveRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "drive",
                serde_json::json!(
                    { "operation" : request.operation, "input" : request.input }
                ),
            )
            .await?;
        checked("drive", status, &body)?;
        Ok(body)
    }

    async fn skills(&self, request: theseus::SkillsRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post("skills", serde_json::json!({ "topic" : request.topic }))
            .await?;
        checked("skills", status, &body)?;
        Ok(body)
    }

    async fn explain(&self, request: theseus::ExplainRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post("explain", serde_json::json!({ "code" : request.code }))
            .await?;
        checked("explain", status, &body)?;
        Ok(body)
    }
}

/// Map a reply's status back onto the contract: 200 passes, 501 is the
/// typed unimplemented default, 403 the typed refusal, anything else the
/// reply's error body.
fn checked(operation: &'static str, status: u16, body: &str) -> anyhow::Result<()> {
    match status {
        200 => Ok(()),
        501 => Err(theseus::Unimplemented(operation).into()),
        403 => Err(theseus::Refused.into()),
        _ => anyhow::bail!("`{operation}` replied {status}: {body}"),
    }
}

fn parsed<T: serde::de::DeserializeOwned>(
    operation: &'static str,
    body: &str,
) -> anyhow::Result<T> {
    serde_json::from_str(body)
        .map_err(|error| anyhow::anyhow!("`{operation}` reply did not parse: {error}"))
}
