// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the HTTP client over the service contract.

/// The service contract carried over HTTP: each call posts its request as
/// a JSON body, and the reply's status maps back onto the contract's error
/// classes. A composition root wires it where an in-process adapter would
/// stand.
pub struct HttpTheseusClient {
    base_url: String,
    http: reqwest::Client,
}

impl HttpTheseusClient {
    /// A client against `base_url`, e.g. `http://127.0.0.1:4870`.
    pub fn new(base_url: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            http: reqwest::Client::new(),
        }
    }

    /// Post one operation call and read the reply.
    async fn post(
        &self,
        operation: &str,
        body: serde_json::Value,
    ) -> anyhow::Result<(u16, String)> {
        let response = self
            .http
            .post(format!("{}/{operation}", self.base_url))
            .json(&body)
            .send()
            .await?;
        let status = response.status().as_u16();
        let body = response.text().await?;
        Ok((status, body))
    }
}

#[async_trait::async_trait]
impl theseus::TheseusService for HttpTheseusClient {
    async fn model(&self) -> anyhow::Result<String> {
        let (status, body) = self.post("model", serde_json::json!({})).await?;
        checked("model", status, &body)?;
        Ok(body)
    }
    async fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        let (status, body) = self.post("verify", serde_json::json!({})).await?;
        checked("verify", status, &body)?;
        parsed("verify", &body)
    }
    async fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let (status, body) = self.post("generate", serde_json::json!({})).await?;
        checked("generate", status, &body)?;
        parsed("generate", &body)
    }
    async fn query(
        &self,
        request: theseus::QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        let (status, body) = self
            .post(
                "query",
                serde_json::json!(
                    { "find" : request.find, "node" : request.node, "kind" : request.kind
                    }
                ),
            )
            .await?;
        checked("query", status, &body)?;
        parsed("query", &body)
    }
    async fn patch(
        &self,
        request: theseus::PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        let (status, body) = self
            .post(
                "patch",
                serde_json::json!({ "edit" : request.edit, "write" : request.write }),
            )
            .await?;
        checked("patch", status, &body)?;
        parsed("patch", &body)
    }
    async fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        let (status, body) = self.post("coverage", serde_json::json!({})).await?;
        checked("coverage", status, &body)?;
        parsed("coverage", &body)
    }
    async fn implement(
        &self,
        request: theseus::ImplementRequest,
    ) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "implement",
                serde_json::json!({ "method" : request.method, "body" : request.body }),
            )
            .await?;
        checked("implement", status, &body)?;
        Ok(body)
    }
    async fn show(&self, request: theseus::ShowRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post("show", serde_json::json!({ "method" : request.method }))
            .await?;
        checked("show", status, &body)?;
        Ok(body)
    }
    async fn check(&self) -> anyhow::Result<String> {
        let (status, body) = self.post("check", serde_json::json!({})).await?;
        checked("check", status, &body)?;
        Ok(body)
    }
    async fn calc(&self, request: theseus::CalcRequest) -> anyhow::Result<String> {
        let (status, body) = self
            .post(
                "calc",
                serde_json::json!(
                    { "op" : request.op, "a" : request.a, "b" : request.b }
                ),
            )
            .await?;
        checked("calc", status, &body)?;
        Ok(body)
    }
    async fn scaffold(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        let (status, body) = self.post("scaffold", serde_json::json!({})).await?;
        checked("scaffold", status, &body)?;
        parsed("scaffold", &body)
    }
}

/// Map a reply's status back onto the contract: 200 passes, 501 is the
/// typed unimplemented default, 403 the typed refusal, anything else the
/// reply's error body.
fn checked(operation: &'static str, status: u16, body: &str) -> anyhow::Result<()> {
    match status {
        200 => Ok(()),
        501 => Err(theseus::Unimplemented(operation).into()),
        403 => Err(theseus_modeling::Refused.into()),
        _ => anyhow::bail!("`{operation}` replied {status}: {body}"),
    }
}

fn parsed<T: serde::de::DeserializeOwned>(
    operation: &'static str,
    body: &str,
) -> anyhow::Result<T> {
    serde_json::from_str(body)
        .map_err(|error| anyhow::anyhow!("`{operation}` reply did not parse: {error}"))
}
