// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the HTTP operation handlers and their status map.

/// One HTTP reply: the status code and the rendered body.
pub struct HttpReply {
    pub status: u16,
    pub content_type: &'static str,
    pub body: String,
}

fn parse_query_request_http(
    input: &serde_json::Value,
) -> anyhow::Result<theseus::QueryRequest> {
    Ok(theseus::QueryRequest {
        find: serde_json::from_value(
                input.get("find").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `find` field is invalid: {error}"))?,
        node: serde_json::from_value(
                input.get("node").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `node` field is invalid: {error}"))?,
        kind: serde_json::from_value(
                input.get("kind").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `kind` field is invalid: {error}"))?,
    })
}

fn parse_patch_request_http(
    input: &serde_json::Value,
) -> anyhow::Result<theseus::PatchRequest> {
    Ok(theseus::PatchRequest {
        edit: match input.get("edit") {
            None => Default::default(),
            Some(value) => {
                serde_json::from_value(value.clone())
                    .map_err(|error| {
                        anyhow::anyhow!("the `edit` field is invalid: {error}")
                    })?
            }
        },
        write: input
            .get("write")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or_default(),
    })
}

fn parse_implement_request_http(
    input: &serde_json::Value,
) -> anyhow::Result<theseus::ImplementRequest> {
    Ok(theseus::ImplementRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        body: input
            .get("body")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `body`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}

fn parse_show_request_http(
    input: &serde_json::Value,
) -> anyhow::Result<theseus::ShowRequest> {
    Ok(theseus::ShowRequest {
        method: input
            .get("method")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `method`"))?,
        port: serde_json::from_value(
                input.get("port").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `port` field is invalid: {error}"))?,
        adapter: serde_json::from_value(
                input.get("adapter").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `adapter` field is invalid: {error}"))?,
    })
}

fn parse_calc_request_http(
    input: &serde_json::Value,
) -> anyhow::Result<theseus::CalcRequest> {
    Ok(theseus::CalcRequest {
        op: input
            .get("op")
            .and_then(serde_json::Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| anyhow::anyhow!("the call needs a string `op`"))?,
        a: serde_json::from_value(
                input.get("a").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `a` field is invalid: {error}"))?,
        b: serde_json::from_value(
                input.get("b").cloned().unwrap_or(serde_json::Value::Null),
            )
            .map_err(|error| anyhow::anyhow!("the `b` field is invalid: {error}"))?,
    })
}

/// Handle one operation call: parse the request from the call's JSON body,
/// run the operation, and render the reply. The status derives from the
/// outcome's structure: 200 a result, 400 a request that does not parse,
/// 404 an unknown operation, 501 an operation with no authored handler,
/// 403 a refused write, and 500 any other error.
pub async fn handle(
    service: &impl theseus::TheseusService,
    name: &str,
    input: &serde_json::Value,
) -> HttpReply {
    match name {
        "model" => reply_text(service.model().await),
        "verify" => reply_json(service.verify().await),
        "generate" => reply_json(service.generate().await),
        "query" => {
            match parse_query_request_http(input) {
                Ok(request) => reply_json(service.query(request).await),
                Err(error) => error_body(400, &error),
            }
        }
        "patch" => {
            match parse_patch_request_http(input) {
                Ok(request) => reply_json(service.patch(request).await),
                Err(error) => error_body(400, &error),
            }
        }
        "coverage" => reply_json(service.coverage().await),
        "implement" => {
            match parse_implement_request_http(input) {
                Ok(request) => reply_text(service.implement(request).await),
                Err(error) => error_body(400, &error),
            }
        }
        "show" => {
            match parse_show_request_http(input) {
                Ok(request) => reply_text(service.show(request).await),
                Err(error) => error_body(400, &error),
            }
        }
        "check" => reply_text(service.check().await),
        "calc" => {
            match parse_calc_request_http(input) {
                Ok(request) => reply_text(service.calc(request).await),
                Err(error) => error_body(400, &error),
            }
        }
        "scaffold" => reply_json(service.scaffold().await),
        "test" => reply_text(service.test().await),
        other => {
            HttpReply {
                status: 404,
                content_type: "application/json",
                body: serde_json::json!(
                    { "error" : format!("unknown operation `{other}`") }
                )
                    .to_string(),
            }
        }
    }
}

fn reply_text(result: anyhow::Result<String>) -> HttpReply {
    match result {
        Ok(body) => {
            HttpReply {
                status: 200,
                content_type: "text/plain; charset=utf-8",
                body,
            }
        }
        Err(error) => error_reply(&error),
    }
}

fn reply_json<T: serde::Serialize>(result: anyhow::Result<T>) -> HttpReply {
    match result {
        Ok(value) => {
            match serde_json::to_string(&value) {
                Ok(body) => {
                    HttpReply {
                        status: 200,
                        content_type: "application/json",
                        body,
                    }
                }
                Err(error) => error_reply(&anyhow::Error::new(error)),
            }
        }
        Err(error) => error_reply(&error),
    }
}

/// The status an operation error maps to, read from the error's type: an
/// operation on its trait default is 501, a write the gate refused is 403,
/// and anything else is 500.
fn error_reply(error: &anyhow::Error) -> HttpReply {
    let status = if error.downcast_ref::<theseus::Unimplemented>().is_some() {
        501
    } else if error.downcast_ref::<theseus::Refused>().is_some() {
        403
    } else {
        500
    };
    error_body(status, error)
}

fn error_body(status: u16, error: &anyhow::Error) -> HttpReply {
    HttpReply {
        status,
        content_type: "application/json",
        body: serde_json::json!({ "error" : error.to_string() }).to_string(),
    }
}
