// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the command surface, request parsers, invocation, and dispatch.

use clap::{Arg, ArgAction, ArgMatches, Command};

/// Build the command surface from the model.
pub fn command() -> Command {
    Command::new("journal")
        .about("The Journal service.")
        .arg_required_else_help(true)
        .subcommand_required(true)
        .subcommand(
            Command::new("add")
                .about("Record one journal entry.")
                .arg(
                    Arg::new("text")
                        .long("text")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The entry to record."),
                ),
        )
        .subcommand(Command::new("list").about("Print every journal entry."))
        .subcommand(
            Command::new("search")
                .about("Print the entries containing a term.")
                .arg(
                    Arg::new("term")
                        .long("term")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The text to look for."),
                ),
        )
}

fn parse_add_request(matches: &ArgMatches) -> anyhow::Result<journal::AddRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(journal::AddRequest {
        text: arg("text").unwrap_or_default(),
    })
}

fn parse_search_request(matches: &ArgMatches) -> anyhow::Result<journal::SearchRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(journal::SearchRequest {
        term: arg("term").unwrap_or_default(),
    })
}

pub enum Invocation {
    Add(journal::AddRequest),
    List,
    Search(journal::SearchRequest),
}

impl Invocation {
    /// Parse the invocation from the matched command line.
    pub fn from_matches(matches: &ArgMatches) -> anyhow::Result<Self> {
        match matches.subcommand() {
            Some(("add", sub)) => Ok(Invocation::Add(parse_add_request(sub)?)),
            Some(("list", _)) => Ok(Invocation::List),
            Some(("search", sub)) => Ok(Invocation::Search(parse_search_request(sub)?)),
            _ => unreachable!("subcommand_required guarantees a subcommand"),
        }
    }
}

/// Dispatch a parsed invocation to the service and render its result:
/// text for a string, otherwise pretty JSON. The authored entry point
/// overrides the operations that need bespoke output and delegates here.
pub async fn dispatch(
    service: &impl journal::JournalService,
    invocation: Invocation,
) -> anyhow::Result<()> {
    match invocation {
        Invocation::Add(request) => println!("{}", service.add(request). await ?),
        Invocation::List => println!("{}", service.list(). await ?),
        Invocation::Search(request) => println!("{}", service.search(request). await ?),
    }
    Ok(())
}
