// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the command surface, request parsers, invocation, and dispatch.

use clap::{Arg, ArgAction, ArgMatches, Command};

/// Build the command surface from the model.
pub fn command() -> Command {
    Command::new("theseus")
        .about("The Theseus service.")
        .arg_required_else_help(true)
        .subcommand_required(true)
        .subcommand(
            Command::new("model").about("Print Theseus's model of itself as JSON."),
        )
        .subcommand(
            Command::new("verify")
                .about("Check that the workspace conforms to its self-model."),
        )
        .subcommand(
            Command::new("generate")
                .about("Regenerate model-derived code from the self-model."),
        )
        .subcommand(
            Command::new("query")
                .about("Return a stable handle and model hash for a model element.")
                .arg(
                    Arg::new("find")
                        .long("find")
                        .action(ArgAction::Set)
                        .help(
                            "Filter handles by a substring of handle, name, kind, or summary.",
                        ),
                )
                .arg(
                    Arg::new("node")
                        .long("node")
                        .action(ArgAction::Set)
                        .help("Narrow to one element by its exact handle."),
                )
                .arg(
                    Arg::new("kind")
                        .long("kind")
                        .action(ArgAction::Set)
                        .help(
                            "Keep only handles of this element kind (operation, type, or port).",
                        ),
                ),
        )
        .subcommand(
            Command::new("patch")
                .about("Propose an edit to the model.")
                .arg(
                    Arg::new("edit")
                        .long("edit")
                        .action(ArgAction::Append)
                        .help(
                            "The edits to apply in order, each a verb over a handle from `query`.",
                        ),
                )
                .arg(
                    Arg::new("write")
                        .long("write")
                        .action(ArgAction::SetTrue)
                        .help(
                            "When true, apply the edit and reproject the model to disk; when false, validate and preview only.",
                        ),
                ),
        )
        .subcommand(
            Command::new("coverage")
                .about("Report which operations have no authored handler."),
        )
        .subcommand(
            Command::new("implement")
                .about(
                    "Splice an authored handler or adapter method and compile-check it.",
                )
                .arg(
                    Arg::new("method")
                        .long("method")
                        .action(ArgAction::Set)
                        .required(true)
                        .help(
                            "Name of the operation — or, with `port`, the port method — to implement.",
                        ),
                )
                .arg(
                    Arg::new("body")
                        .long("body")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The handler body to splice into the impl."),
                )
                .arg(
                    Arg::new("port")
                        .long("port")
                        .action(ArgAction::Set)
                        .help("Name of the port whose adapter method to implement."),
                )
                .arg(
                    Arg::new("adapter")
                        .long("adapter")
                        .action(ArgAction::Set)
                        .help(
                            "The adapter type to target when the file holds more than one.",
                        ),
                ),
        )
        .subcommand(
            Command::new("show")
                .about("Show an operation's current handler source.")
                .arg(
                    Arg::new("method")
                        .long("method")
                        .action(ArgAction::Set)
                        .required(true)
                        .help(
                            "Name of the operation — or, with `port`, the port method — to show.",
                        ),
                )
                .arg(
                    Arg::new("port")
                        .long("port")
                        .action(ArgAction::Set)
                        .help("Name of the port whose adapter method to show."),
                )
                .arg(
                    Arg::new("adapter")
                        .long("adapter")
                        .action(ArgAction::Set)
                        .help(
                            "The adapter type to target when the file holds more than one.",
                        ),
                ),
        )
        .subcommand(
            Command::new("check")
                .about("Compile-check the workspace and report the outcome."),
        )
        .subcommand(
            Command::new("calc")
                .about(
                    "Evaluate an arithmetic expression through the calculator service.",
                )
                .arg(
                    Arg::new("op")
                        .long("op")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The operator: add, subtract, multiply, or divide."),
                )
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
        .subcommand(
            Command::new("scaffold")
                .about(
                    "Write the skeleton of each library service crate that is missing it.",
                ),
        )
        .subcommand(
            Command::new("test").about("Run the workspace tests and report the outcome."),
        )
        .subcommand(
            Command::new("snapshot")
                .about(
                    "Checkpoint tracked files and exact model-owned working-tree state, and return the snapshot id.",
                )
                .arg(
                    Arg::new("label")
                        .long("label")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("A short label naming the snapshot."),
                ),
        )
        .subcommand(
            Command::new("rollback")
                .about(
                    "Restore tracked files and exact model-owned working-tree state from a snapshot.",
                )
                .arg(
                    Arg::new("reference")
                        .long("reference")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The snapshot id, as returned by `snapshot`."),
                ),
        )
        .subcommand(
            Command::new("release")
                .about("Release a snapshot that is no longer needed.")
                .arg(
                    Arg::new("reference")
                        .long("reference")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The snapshot id, as returned by `snapshot`."),
                ),
        )
        .subcommand(
            Command::new("prune")
                .about("Release older snapshots beyond a retention limit.")
                .arg(
                    Arg::new("keep")
                        .long("keep")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(u32))
                        .help("Number of newest snapshots to retain."),
                ),
        )
        .subcommand(
            Command::new("diff")
                .about("Show what changed in the working tree since a snapshot.")
                .arg(
                    Arg::new("reference")
                        .long("reference")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The snapshot id, as returned by `snapshot`."),
                ),
        )
        .subcommand(
            Command::new("restart")
                .about("Compile-check readiness for an inbound-managed process restart."),
        )
        .subcommand(
            Command::new("read")
                .about("Read a workspace file, capped for a tool result.")
                .arg(
                    Arg::new("path")
                        .long("path")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The workspace-relative file to read."),
                ),
        )
        .subcommand(
            Command::new("search")
                .about("Find a pattern's occurrences across the workspace.")
                .arg(
                    Arg::new("pattern")
                        .long("pattern")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The text to find."),
                )
                .arg(
                    Arg::new("path")
                        .long("path")
                        .action(ArgAction::Set)
                        .help(
                            "A workspace-relative subtree to search. The whole workspace when omitted.",
                        ),
                ),
        )
        .subcommand(
            Command::new("list")
                .about("List a workspace directory.")
                .arg(
                    Arg::new("path")
                        .long("path")
                        .action(ArgAction::Set)
                        .help(
                            "The workspace-relative directory to list. The root when omitted.",
                        ),
                ),
        )
        .subcommand(
            Command::new("lint")
                .about("Run clippy across the workspace with warnings denied."),
        )
}

fn parse_query_request(matches: &ArgMatches) -> anyhow::Result<theseus::QueryRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::QueryRequest {
        find: arg("find"),
        node: arg("node"),
        kind: arg("kind"),
    })
}

fn parse_patch_request(matches: &ArgMatches) -> anyhow::Result<theseus::PatchRequest> {
    Ok(theseus::PatchRequest {
        edit: matches
            .get_many::<String>("edit")
            .map(|values| {
                values
                    .map(|value| value.parse::<theseus_modeling::Edit>())
                    .collect::<Result<Vec<_>, _>>()
            })
            .transpose()?
            .unwrap_or_default(),
        write: matches.get_flag("write"),
    })
}

fn parse_implement_request(
    matches: &ArgMatches,
) -> anyhow::Result<theseus::ImplementRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::ImplementRequest {
        method: arg("method").unwrap_or_default(),
        body: arg("body").unwrap_or_default(),
        port: arg("port"),
        adapter: arg("adapter"),
    })
}

fn parse_show_request(matches: &ArgMatches) -> anyhow::Result<theseus::ShowRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::ShowRequest {
        method: arg("method").unwrap_or_default(),
        port: arg("port"),
        adapter: arg("adapter"),
    })
}

fn parse_calc_request(matches: &ArgMatches) -> anyhow::Result<theseus::CalcRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::CalcRequest {
        op: arg("op").unwrap_or_default(),
        a: matches.get_one::<f64>("a").cloned().unwrap_or_default(),
        b: matches.get_one::<f64>("b").cloned().unwrap_or_default(),
    })
}

fn parse_snapshot_request(
    matches: &ArgMatches,
) -> anyhow::Result<theseus::SnapshotRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::SnapshotRequest {
        label: arg("label").unwrap_or_default(),
    })
}

fn parse_snapshot_ref(matches: &ArgMatches) -> anyhow::Result<theseus::SnapshotRef> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::SnapshotRef {
        reference: arg("reference").unwrap_or_default(),
    })
}

fn parse_snapshot_retention(
    matches: &ArgMatches,
) -> anyhow::Result<theseus::SnapshotRetention> {
    Ok(theseus::SnapshotRetention {
        keep: matches.get_one::<u32>("keep").cloned().unwrap_or_default(),
    })
}

fn parse_read_request(matches: &ArgMatches) -> anyhow::Result<theseus::ReadRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::ReadRequest {
        path: arg("path").unwrap_or_default(),
    })
}

fn parse_search_request(matches: &ArgMatches) -> anyhow::Result<theseus::SearchRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::SearchRequest {
        pattern: arg("pattern").unwrap_or_default(),
        path: arg("path"),
    })
}

fn parse_list_request(matches: &ArgMatches) -> anyhow::Result<theseus::ListRequest> {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    Ok(theseus::ListRequest {
        path: arg("path"),
    })
}

pub enum Invocation {
    Model,
    Verify,
    Generate,
    Query(theseus::QueryRequest),
    Patch(theseus::PatchRequest),
    Coverage,
    Implement(theseus::ImplementRequest),
    Show(theseus::ShowRequest),
    Check,
    Calc(theseus::CalcRequest),
    Scaffold,
    Test,
    Snapshot(theseus::SnapshotRequest),
    Rollback(theseus::SnapshotRef),
    Release(theseus::SnapshotRef),
    Prune(theseus::SnapshotRetention),
    Diff(theseus::SnapshotRef),
    Restart,
    Read(theseus::ReadRequest),
    Search(theseus::SearchRequest),
    List(theseus::ListRequest),
    Lint,
}

impl Invocation {
    /// Parse the invocation from the matched command line.
    pub fn from_matches(matches: &ArgMatches) -> anyhow::Result<Self> {
        match matches.subcommand() {
            Some(("model", _)) => Ok(Invocation::Model),
            Some(("verify", _)) => Ok(Invocation::Verify),
            Some(("generate", _)) => Ok(Invocation::Generate),
            Some(("query", sub)) => Ok(Invocation::Query(parse_query_request(sub)?)),
            Some(("patch", sub)) => Ok(Invocation::Patch(parse_patch_request(sub)?)),
            Some(("coverage", _)) => Ok(Invocation::Coverage),
            Some(("implement", sub)) => {
                Ok(Invocation::Implement(parse_implement_request(sub)?))
            }
            Some(("show", sub)) => Ok(Invocation::Show(parse_show_request(sub)?)),
            Some(("check", _)) => Ok(Invocation::Check),
            Some(("calc", sub)) => Ok(Invocation::Calc(parse_calc_request(sub)?)),
            Some(("scaffold", _)) => Ok(Invocation::Scaffold),
            Some(("test", _)) => Ok(Invocation::Test),
            Some(("snapshot", sub)) => {
                Ok(Invocation::Snapshot(parse_snapshot_request(sub)?))
            }
            Some(("rollback", sub)) => Ok(Invocation::Rollback(parse_snapshot_ref(sub)?)),
            Some(("release", sub)) => Ok(Invocation::Release(parse_snapshot_ref(sub)?)),
            Some(("prune", sub)) => Ok(Invocation::Prune(parse_snapshot_retention(sub)?)),
            Some(("diff", sub)) => Ok(Invocation::Diff(parse_snapshot_ref(sub)?)),
            Some(("restart", _)) => Ok(Invocation::Restart),
            Some(("read", sub)) => Ok(Invocation::Read(parse_read_request(sub)?)),
            Some(("search", sub)) => Ok(Invocation::Search(parse_search_request(sub)?)),
            Some(("list", sub)) => Ok(Invocation::List(parse_list_request(sub)?)),
            Some(("lint", _)) => Ok(Invocation::Lint),
            _ => unreachable!("subcommand_required guarantees a subcommand"),
        }
    }
}

/// Dispatch a parsed invocation to the service and render its result:
/// text for a string, otherwise pretty JSON. The authored entry point
/// overrides the operations that need bespoke output and delegates here.
pub async fn dispatch(
    service: &impl theseus::TheseusService,
    invocation: Invocation,
) -> anyhow::Result<()> {
    match invocation {
        Invocation::Model => println!("{}", service.model(). await ?),
        Invocation::Verify => {
            println!("{}", serde_json::to_string_pretty(& service.verify(). await ?) ?)
        }
        Invocation::Generate => {
            println!("{}", serde_json::to_string_pretty(& service.generate(). await ?) ?)
        }
        Invocation::Query(request) => {
            println!(
                "{}", serde_json::to_string_pretty(& service.query(request). await ?) ?
            )
        }
        Invocation::Patch(request) => {
            println!(
                "{}", serde_json::to_string_pretty(& service.patch(request). await ?) ?
            )
        }
        Invocation::Coverage => {
            println!("{}", serde_json::to_string_pretty(& service.coverage(). await ?) ?)
        }
        Invocation::Implement(request) => {
            println!(
                "{}", serde_json::to_string_pretty(& service.implement(request). await ?)
                ?
            )
        }
        Invocation::Show(request) => println!("{}", service.show(request). await ?),
        Invocation::Check => {
            println!("{}", serde_json::to_string_pretty(& service.check(). await ?) ?)
        }
        Invocation::Calc(request) => println!("{}", service.calc(request). await ?),
        Invocation::Scaffold => {
            println!("{}", serde_json::to_string_pretty(& service.scaffold(). await ?) ?)
        }
        Invocation::Test => {
            println!("{}", serde_json::to_string_pretty(& service.test(). await ?) ?)
        }
        Invocation::Snapshot(request) => {
            println!("{}", service.snapshot(request). await ?)
        }
        Invocation::Rollback(request) => {
            println!("{}", service.rollback(request). await ?)
        }
        Invocation::Release(request) => println!("{}", service.release(request). await ?),
        Invocation::Prune(request) => println!("{}", service.prune(request). await ?),
        Invocation::Diff(request) => println!("{}", service.diff(request). await ?),
        Invocation::Restart => {
            println!("{}", serde_json::to_string_pretty(& service.restart(). await ?) ?)
        }
        Invocation::Read(request) => println!("{}", service.read(request). await ?),
        Invocation::Search(request) => println!("{}", service.search(request). await ?),
        Invocation::List(request) => println!("{}", service.list(request). await ?),
        Invocation::Lint => {
            println!("{}", serde_json::to_string_pretty(& service.lint(). await ?) ?)
        }
    }
    Ok(())
}
