// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: command surface, request types, invocation, service contract, outbound ports, composition root.

use clap::{Arg, ArgAction, ArgMatches, Command};
/// Build the command surface from the model.
pub fn command() -> Command {
    Command::new("theseus")
        .about("A self-modeling CLI seed.")
        .arg_required_else_help(true)
        .subcommand(
            Command::new("model").about("Print Theseus's model of itself as JSON."),
        )
        .subcommand(
            Command::new("verify")
                .about("Check that the workspace conforms to its self-model."),
        )
        .subcommand(
            Command::new("generate")
                .about("Regenerate model-derived code from the self-model."),
        )
        .subcommand(
            Command::new("query")
                .about("Return a stable handle and model hash for a model element.")
                .arg(
                    Arg::new("find")
                        .long("find")
                        .action(ArgAction::Set)
                        .help(
                            "Filter handles by a substring of handle, name, kind, or summary.",
                        ),
                )
                .arg(
                    Arg::new("node")
                        .long("node")
                        .action(ArgAction::Set)
                        .help("Narrow to one element by its exact handle."),
                )
                .arg(
                    Arg::new("kind")
                        .long("kind")
                        .action(ArgAction::Set)
                        .help(
                            "Keep only handles of this element kind (operation, type, or port).",
                        ),
                ),
        )
        .subcommand(
            Command::new("patch")
                .about("Propose a hash-checked edit to the model.")
                .arg(
                    Arg::new("verb")
                        .long("verb")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The verb: add, remove, rename, or set."),
                )
                .arg(
                    Arg::new("target")
                        .long("target")
                        .action(ArgAction::Set)
                        .required(true)
                        .help(
                            "Handle of the parent, for add; of the node, for remove, rename, and set.",
                        ),
                )
                .arg(
                    Arg::new("kind")
                        .long("kind")
                        .action(ArgAction::Set)
                        .help(
                            "Node kind to add: operation, type, port, method, field, or variant.",
                        ),
                )
                .arg(
                    Arg::new("name")
                        .long("name")
                        .action(ArgAction::Set)
                        .help("Name of the node to add."),
                )
                .arg(
                    Arg::new("to")
                        .long("to")
                        .action(ArgAction::Set)
                        .help("New name, for rename."),
                )
                .arg(
                    Arg::new("set")
                        .long("set")
                        .action(ArgAction::Append)
                        .help(
                            "A `key=value` scalar assignment, repeatable, for add and set.",
                        ),
                )
                .arg(
                    Arg::new("expect-model-hash")
                        .long("expect-model-hash")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The model hash the edit was computed against."),
                )
                .arg(
                    Arg::new("write")
                        .long("write")
                        .action(ArgAction::SetTrue)
                        .help("Apply the edit by reprojecting the model."),
                ),
        )
        .subcommand(
            Command::new("coverage")
                .about("Report which operations have an authored handler."),
        )
}
/// Writes generated files into the workspace.
pub trait Workspace {
    /// Write one generated file to disk.
    fn write_file(
        &self,
        request: &theseus_modeling::GeneratedFile,
    ) -> anyhow::Result<()>;
}
/// Composition root: the model plus the wired outbound ports.
pub struct Ctx<'a> {
    pub model: &'a theseus_modeling::Model,
    pub workspace: &'a dyn Workspace,
}
/// The `QueryRequest` request, parsed from command-line arguments.
#[derive(Debug, Clone)]
pub struct QueryRequest {
    /// Filter handles by a substring of handle, name, kind, or summary.
    pub find: Option<String>,
    /// Narrow to one element by its exact handle.
    pub node: Option<String>,
    /// Keep only handles of this element kind (operation, type, or port).
    pub kind: Option<String>,
}
impl QueryRequest {
    /// Build the request from parsed command-line arguments.
    fn from_matches(matches: &ArgMatches) -> Self {
        let arg = |name: &str| matches.get_one::<String>(name).cloned();
        QueryRequest {
            find: arg("find"),
            node: arg("node"),
            kind: arg("kind"),
        }
    }
}
/// The `PatchRequest` request, parsed from command-line arguments.
#[derive(Debug, Clone)]
pub struct PatchRequest {
    /// The verb: add, remove, rename, or set.
    pub verb: String,
    /// Handle of the parent, for add; of the node, for remove, rename, and set.
    pub target: String,
    /// Node kind to add: operation, type, port, method, field, or variant.
    pub kind: Option<String>,
    /// Name of the node to add.
    pub name: Option<String>,
    /// New name, for rename.
    pub to: Option<String>,
    /// A `key=value` scalar assignment, repeatable, for add and set.
    pub set: Vec<String>,
    /// The model hash the edit was computed against.
    pub expect_model_hash: String,
    /// Apply the edit by reprojecting the model.
    pub write: bool,
}
impl PatchRequest {
    /// Build the request from parsed command-line arguments.
    fn from_matches(matches: &ArgMatches) -> Self {
        let arg = |name: &str| matches.get_one::<String>(name).cloned();
        PatchRequest {
            verb: arg("verb").unwrap_or_default(),
            target: arg("target").unwrap_or_default(),
            kind: arg("kind"),
            name: arg("name"),
            to: arg("to"),
            set: matches
                .get_many::<String>("set")
                .map(|values| values.cloned().collect())
                .unwrap_or_default(),
            expect_model_hash: arg("expect-model-hash").unwrap_or_default(),
            write: matches.get_flag("write"),
        }
    }
}
/// A parsed invocation: one variant per operation, carrying its request.
pub enum Invocation {
    /// Print Theseus's model of itself as JSON.
    Model,
    /// Check that the workspace conforms to its self-model.
    Verify,
    /// Regenerate model-derived code from the self-model.
    Generate,
    /// Return a stable handle and model hash for a model element.
    Query(QueryRequest),
    /// Propose a hash-checked edit to the model.
    Patch(PatchRequest),
    /// Report which operations have an authored handler.
    Coverage,
}
impl Invocation {
    /// Parse the invocation from the matched command line.
    pub fn from_matches(matches: &ArgMatches) -> Self {
        match matches.subcommand() {
            Some(("model", _)) => Invocation::Model,
            Some(("verify", _)) => Invocation::Verify,
            Some(("generate", _)) => Invocation::Generate,
            Some(("query", sub)) => Invocation::Query(QueryRequest::from_matches(sub)),
            Some(("patch", sub)) => Invocation::Patch(PatchRequest::from_matches(sub)),
            Some(("coverage", _)) => Invocation::Coverage,
            _ => unreachable!("arg_required_else_help guarantees a subcommand"),
        }
    }
}
/// The inbound service contract: one method per operation, each defaulting
/// to `unimplemented`. The authored impl overrides what it implements.
pub trait TheseusService {
    /// Print Theseus's model of itself as JSON.
    fn model(&self) -> anyhow::Result<String> {
        anyhow::bail!("unimplemented operation: model")
    }
    /// Check that the workspace conforms to its self-model.
    fn verify(&self) -> anyhow::Result<theseus_modeling::VerifyReport> {
        anyhow::bail!("unimplemented operation: verify")
    }
    /// Regenerate model-derived code from the self-model.
    fn generate(&self) -> anyhow::Result<Vec<theseus_modeling::GeneratedFile>> {
        anyhow::bail!("unimplemented operation: generate")
    }
    /// Return a stable handle and model hash for a model element.
    fn query(
        &self,
        _request: QueryRequest,
    ) -> anyhow::Result<theseus_modeling::QueryOutcome> {
        anyhow::bail!("unimplemented operation: query")
    }
    /// Propose a hash-checked edit to the model.
    fn patch(
        &self,
        _request: PatchRequest,
    ) -> anyhow::Result<theseus_modeling::PatchOutcome> {
        anyhow::bail!("unimplemented operation: patch")
    }
    /// Report which operations have an authored handler.
    fn coverage(&self) -> anyhow::Result<theseus_modeling::CoverageReport> {
        anyhow::bail!("unimplemented operation: coverage")
    }
}
