// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the command surface, request parsers, invocation, and dispatch.

use clap::{Arg, ArgAction, ArgMatches, Command};

/// Build the command surface from the model.
pub fn command() -> Command {
    Command::new("theseus")
        .about("The Theseus service.")
        .arg_required_else_help(true)
        .subcommand(
            Command::new("model").about("Print Theseus's model of itself as JSON."),
        )
        .subcommand(
            Command::new("verify")
                .about("Check that the workspace conforms to its self-model."),
        )
        .subcommand(
            Command::new("generate")
                .about("Regenerate model-derived code from the self-model."),
        )
        .subcommand(
            Command::new("query")
                .about("Return a stable handle and model hash for a model element.")
                .arg(
                    Arg::new("find")
                        .long("find")
                        .action(ArgAction::Set)
                        .help(
                            "Filter handles by a substring of handle, name, kind, or summary.",
                        ),
                )
                .arg(
                    Arg::new("node")
                        .long("node")
                        .action(ArgAction::Set)
                        .help("Narrow to one element by its exact handle."),
                )
                .arg(
                    Arg::new("kind")
                        .long("kind")
                        .action(ArgAction::Set)
                        .help(
                            "Keep only handles of this element kind (operation, type, or port).",
                        ),
                ),
        )
        .subcommand(
            Command::new("patch")
                .about("Propose an edit to the model.")
                .arg(
                    Arg::new("edit")
                        .long("edit")
                        .action(ArgAction::Append)
                        .help(
                            "A pipe-separated edit `verb|target|key=value...`, repeatable, applied in order.",
                        ),
                )
                .arg(
                    Arg::new("write")
                        .long("write")
                        .action(ArgAction::SetTrue)
                        .help("Apply the edit by reprojecting the model."),
                ),
        )
        .subcommand(
            Command::new("coverage")
                .about("Report which operations have an authored handler."),
        )
        .subcommand(
            Command::new("implement")
                .about("Splice an authored handler for an unimplemented operation.")
                .arg(
                    Arg::new("method")
                        .long("method")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("Name of the operation to implement."),
                )
                .arg(
                    Arg::new("body")
                        .long("body")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The handler body to splice into the impl."),
                ),
        )
        .subcommand(
            Command::new("show")
                .about("Show an operation's current handler source.")
                .arg(
                    Arg::new("method")
                        .long("method")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("Name of the operation whose handler to show."),
                ),
        )
        .subcommand(
            Command::new("calc")
                .about(
                    "Evaluate an arithmetic expression through the calculator service.",
                )
                .arg(
                    Arg::new("op")
                        .long("op")
                        .action(ArgAction::Set)
                        .required(true)
                        .help("The operator: add, subtract, multiply, or divide."),
                )
                .arg(
                    Arg::new("a")
                        .long("a")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Left operand."),
                )
                .arg(
                    Arg::new("b")
                        .long("b")
                        .action(ArgAction::Set)
                        .required(true)
                        .value_parser(clap::value_parser!(f64))
                        .help("Right operand."),
                ),
        )
        .subcommand(
            Command::new("scaffold")
                .about(
                    "Write the skeleton of each library service crate that is missing it.",
                ),
        )
}

fn parse_queryrequest(matches: &ArgMatches) -> theseus::QueryRequest {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    theseus::QueryRequest {
        find: arg("find"),
        node: arg("node"),
        kind: arg("kind"),
    }
}

fn parse_patchrequest(matches: &ArgMatches) -> theseus::PatchRequest {
    theseus::PatchRequest {
        edit: matches
            .get_many::<String>("edit")
            .map(|values| values.cloned().collect())
            .unwrap_or_default(),
        write: matches.get_flag("write"),
    }
}

fn parse_implementrequest(matches: &ArgMatches) -> theseus::ImplementRequest {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    theseus::ImplementRequest {
        method: arg("method").unwrap_or_default(),
        body: arg("body").unwrap_or_default(),
    }
}

fn parse_showrequest(matches: &ArgMatches) -> theseus::ShowRequest {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    theseus::ShowRequest {
        method: arg("method").unwrap_or_default(),
    }
}

fn parse_calcrequest(matches: &ArgMatches) -> theseus::CalcRequest {
    let arg = |name: &str| matches.get_one::<String>(name).cloned();
    theseus::CalcRequest {
        op: arg("op").unwrap_or_default(),
        a: matches.get_one::<f64>("a").cloned().unwrap_or_default(),
        b: matches.get_one::<f64>("b").cloned().unwrap_or_default(),
    }
}

pub enum Invocation {
    Model,
    Verify,
    Generate,
    Query(theseus::QueryRequest),
    Patch(theseus::PatchRequest),
    Coverage,
    Implement(theseus::ImplementRequest),
    Show(theseus::ShowRequest),
    Calc(theseus::CalcRequest),
    Scaffold,
}

impl Invocation {
    /// Parse the invocation from the matched command line.
    pub fn from_matches(matches: &ArgMatches) -> Self {
        match matches.subcommand() {
            Some(("model", _)) => Invocation::Model,
            Some(("verify", _)) => Invocation::Verify,
            Some(("generate", _)) => Invocation::Generate,
            Some(("query", sub)) => Invocation::Query(parse_queryrequest(sub)),
            Some(("patch", sub)) => Invocation::Patch(parse_patchrequest(sub)),
            Some(("coverage", _)) => Invocation::Coverage,
            Some(("implement", sub)) => {
                Invocation::Implement(parse_implementrequest(sub))
            }
            Some(("show", sub)) => Invocation::Show(parse_showrequest(sub)),
            Some(("calc", sub)) => Invocation::Calc(parse_calcrequest(sub)),
            Some(("scaffold", _)) => Invocation::Scaffold,
            _ => unreachable!("arg_required_else_help guarantees a subcommand"),
        }
    }
}

/// Dispatch a parsed invocation to the service and render its result:
/// text for a string, otherwise pretty JSON. The authored entry point
/// overrides the operations that need bespoke output and delegates here.
pub fn dispatch(
    service: &impl theseus::TheseusService,
    invocation: Invocation,
) -> anyhow::Result<()> {
    match invocation {
        Invocation::Model => println!("{}", service.model() ?),
        Invocation::Verify => {
            println!("{}", serde_json::to_string_pretty(& service.verify() ?) ?)
        }
        Invocation::Generate => {
            println!("{}", serde_json::to_string_pretty(& service.generate() ?) ?)
        }
        Invocation::Query(request) => {
            println!("{}", serde_json::to_string_pretty(& service.query(request) ?) ?)
        }
        Invocation::Patch(request) => {
            println!("{}", serde_json::to_string_pretty(& service.patch(request) ?) ?)
        }
        Invocation::Coverage => {
            println!("{}", serde_json::to_string_pretty(& service.coverage() ?) ?)
        }
        Invocation::Implement(request) => println!("{}", service.implement(request) ?),
        Invocation::Show(request) => println!("{}", service.show(request) ?),
        Invocation::Calc(request) => println!("{}", service.calc(request) ?),
        Invocation::Scaffold => {
            println!("{}", serde_json::to_string_pretty(& service.scaffold() ?) ?)
        }
    }
    Ok(())
}
