// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the gRPC service glue and its status map.

/// The wire types and service glue the build compiles from the proto.
pub mod proto {
    tonic::include_proto!("theseus.calculator");
}

/// The service glue: the transport's generated server trait, implemented
/// over any implementation of the service contract.
pub struct GrpcCalculator<S>(pub S);

#[tonic::async_trait]
impl<
    S: theseus_calculator::CalculatorService + Send + Sync + 'static,
> proto::calculator_server::Calculator for GrpcCalculator<S> {
    async fn add(
        &self,
        request: tonic::Request<proto::Operands>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .add(theseus_calculator::Operands {
                a: request.a,
                b: request.b,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn subtract(
        &self,
        request: tonic::Request<proto::Operands>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .subtract(theseus_calculator::Operands {
                a: request.a,
                b: request.b,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn multiply(
        &self,
        request: tonic::Request<proto::Operands>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .multiply(theseus_calculator::Operands {
                a: request.a,
                b: request.b,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }

    async fn divide(
        &self,
        request: tonic::Request<proto::Operands>,
    ) -> Result<tonic::Response<proto::CalcResult>, tonic::Status> {
        let request = request.into_inner();
        let outcome = self
            .0
            .divide(theseus_calculator::Operands {
                a: request.a,
                b: request.b,
            })
            .await;
        match outcome {
            Ok(value) => Ok(tonic::Response::new(proto::CalcResult { value })),
            Err(error) => Err(status(&error)),
        }
    }
}

/// The status an operation error maps to, read from the error's type: an
/// operation on its trait default is UNIMPLEMENTED, a write the gate refused
/// is PERMISSION_DENIED, and anything else is INTERNAL.
fn status(error: &anyhow::Error) -> tonic::Status {
    if error.downcast_ref::<theseus_calculator::Unimplemented>().is_some() {
        tonic::Status::unimplemented(error.to_string())
    } else if error.downcast_ref::<theseus_calculator::Refused>().is_some() {
        tonic::Status::permission_denied(error.to_string())
    } else {
        tonic::Status::internal(error.to_string())
    }
}
