// @generated by `theseus generate` — do not edit by hand.
//! Theseus's generated scaffolding: the loop's port contract and turn budget.

/// Completes one turn of the conversation.
#[async_trait::async_trait]
pub trait Llm: Send + Sync {
    /// Complete one turn from the transcript and the tool catalog.
    async fn complete(&self, _request: &Turn) -> anyhow::Result<crate::agent::Reply> {
        Err(Unimplemented("llm.complete").into())
    }
}

/// A borrowed adapter serves the port its target serves, so a wrapper
/// generic over the port holds a borrow as readily as an owned adapter.
#[async_trait::async_trait]
impl<T: Llm + ?Sized> Llm for &T {
    async fn complete(&self, request: &Turn) -> anyhow::Result<crate::agent::Reply> {
        (**self).complete(request).await
    }
}

/// The most turns the loop runs before giving up.
pub const TURN_BUDGET: usize = 32;

/// The `Turn` request.
#[derive(Debug, Clone)]
pub struct Turn {
    /// The framing handed to the model.
    pub system: String,
    /// The conversation so far.
    pub messages: Vec<crate::agent::Message>,
    /// The tool catalog the model may call.
    pub tools: Vec<serde_json::Value>,
}

/// An operation with no authored handler, the trait default's error. A
/// transport adapter downcasts it to map the outcome in its own vocabulary.
#[derive(Debug)]
pub struct Unimplemented(pub &'static str);

impl std::fmt::Display for Unimplemented {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unimplemented operation: {}", self.0)
    }
}

impl std::error::Error for Unimplemented {}
